### ISSUE TITLE
Problème avec le firmware 3.0b

### ISSUE THREAD

**Issue by dams74** [fairecasoimeme/ZiGate#10]
Bonjour
Pour commencer merci pour le travail effectué.
Lors de la mise à jour du firmware 3.0b, j'ai le message suivant: the firmware file was built for another processor version and might not run on the connected device.
Voir capure ci dessous.
![pb firm 3 0b](https://user-images.githubusercontent.com/2788955/35192049-d5e09e34-fe89-11e7-998b-65704292089b.JPG)
J'ai essayé de mettre les firmware 3.0 et 3.0a et tout passe sans message d'erreur ou d'avertissement.
Damien

**Comment by ioull** [comment]
Tu as essayé de re télécharger le firmware 3.0b ? J’ai eu le même soucis et ça venait de mon fichier corrompu.

**Comment by dams74** [comment]
En effet le problème viens bien de mon fichier...
Pourquoi n'ai-je pas pensé à le télécharger de nouveau...
Merci bien en tout cas.
Damien
