### ISSUE TITLE
0x8006 not interpretated by ZGUI

### ISSUE THREAD

**Issue by pipiche38** [fairecasoimeme/ZiGate#101]
When doing a 'Reset' , while all 0x8003/0x8004/0x8005 are correctly interated in the Message View, this is not the case for 0x8006

`Type: 0x8006 (Unrecognized)`

**Comment by ISO-B** [comment]
At the moment correct values are:
0x00 for STARTUP
0x01 for RUNNING if firmware has built without FULL_FUNC_DEVICE flag. If flag is used then 0x01 is NFN_START and 0x02 is RUNNING.

It would be best to change code so 0x01 would be always RUNNING and 0x02 would be NFN_START

**Comment by pipiche38** [comment]
Will update on my side with 0x01 = running

**Comment by pipiche38** [comment]
thanks

**Comment by ISO-B** [comment]
@fairecasoimeme just to notify you that documentation needs update.

**Comment by fairecasoimeme** [comment]
ok thanks, I added to my todolist ;)

**Comment by fairecasoimeme** [comment]
Finally, I updated
