### ISSUE TITLE
Does write attribute request support multiple attributes ? (command 0x0110)

### ISSUE THREAD

**Issue by doudz** [fairecasoimeme/ZiGate#115]
Documentation says that write attribute request supports multiple attributes writing in the same request (attributes list)
But looking at firmware code I don't think so
https://github.com/fairecasoimeme/ZiGate/blob/master/Module%20Radio/Firmware/src/ZiGate/Source/ZigbeeNodeControlBridge/app_Znc_cmds.c#L1840

Can you confirm ?

**Comment by fairecasoimeme** [comment]
I confirm :(

**Comment by doudz** [comment]
So, could you just update documentation ?

**Comment by ISO-B** [comment]
I don't think that documentation need update.  Case that handles E_SL_MSG_WRITE ATTRIBUTE_REQUEST send data to APP_eSendWriteAttributesRequest. 
https://github.com/fairecasoimeme/ZiGate/blob/76c328bb44a6fdd1774c86807b101c9c15edfebc/Module%20Radio/Firmware/src/ZiGate/Source/ZigbeeNodeControlBridge/app_Znc_cmds.c#L3504-L3624

For me it seems that it should be able to handle attributes list, see lines 3585-3603.

**Comment by fairecasoimeme** [comment]
won't fix because not necessary
