### ISSUE TITLE
adding addr in the 8000 response message

### ISSUE THREAD

**Issue by pipiche38** [fairecasoimeme/ZiGate#116]
Is it possible to get the short address the response is related too ?

**Comment by doudz** [comment]
I don't think it's relevant since some command use response 8000 but not related to any device addr, example command 0x0010 (get version)

**Comment by fairecasoimeme** [comment]
It's not so easy because Status message don't necessarily concern a device.

**Comment by fairecasoimeme** [comment]
lol in the same time @doudz

**Comment by doudz** [comment]
yes lol ;)

**Comment by pipiche38** [comment]
As the SQN for non device related we could adopt a similar approach.

**Comment by doudz** [comment]
SQN? Rssi , no?

**Comment by pipiche38** [comment]
Exact RSSI.

de plus en mettant 0x0000 comme Network Address dans ce message, cela reste cohérent puisque la Short Address de la Zigate est en principe 0x0000

**Comment by pipiche38** [comment]
I don't think that this one as been targeted in 3.0f firmware. So still Open

**Comment by pipiche38** [comment]
It would be great if we could have it on 3.10 ?

**Comment by doudz** [comment]
For me it's not relevant

**Comment by pipiche38** [comment]
It might not be relevant for you, but could be for some others.
0x8000 is an async response to a command , and I would consider that the short addr should be part of the response.

**Comment by ISO-B** [comment]
Adding value to response won't be be problem if we remove that optional error string which is not actually used #163. All commands that don't need target address would need to be flagged somehow to be ZiGate specific and would return address of ZiGate. Quick solution to this would assume that all commands are sent to u16 address and just add u16 address to end of 0x8000 response.

Most commands can also be sent to bind address or group address too so it would be logical to add address mode also. If or when we decide to do #157 it would be mandatory to add address mode.

@pipiche38 Can you tell me why this is needed or what is use case for this? Just so I can better understand and plan how to test this when starting to work on this.

**Comment by pipiche38** [comment]
As stated, there is no need to keep this Issue open. This was for the purpose of the : 
- Consistency with all responses got from Zigate
- To allow asynchronus mechanism work

**Comment by ISO-B** [comment]
Ok. I see this is important if someone wants to use ZiGate asynchronously.

**Comment by pipiche38** [comment]
Up, thanks !

**Comment by pipiche38** [comment]
Up, thanks !

**Comment by pipiche38** [comment]
Up thanks

**Comment by pipiche38** [comment]
Fixed with 31d, SQN APS,ZCL implement
