### ISSUE TITLE
Zigate ne transmet plus les Basic: Report Attributes du Xiaomi Door Sensor 

### ISSUE THREAD

**Issue by KiwiHC16** [fairecasoimeme/ZiGate#12]
De temps en temps  la Zigate recoit un message du Xiaomi Door Sensor (visible sur sniff zigbee) sur un appuie du bouton lateral et ne le transmet pas sur le port USB.
Solution de contournement trouvée, mettre la zigate en association et re-associer le bouton.
Un reset (cmd reset) de la Zigate ne suffit pas.

**Comment by fairecasoimeme** [comment]
I will test but I never see before this kind of bug.

**Comment by KiwiHC16** [comment]
Not seen this issue for days. So I close it.
