### ISSUE TITLE
Sauvegardez et restaurez votre ZiGate sur Linux

### ISSUE THREAD

**Issue by lboue** [fairecasoimeme/ZiGate#120]
Bonjour,

Pourriez-vous m'indiquer l'outil à utiliser pour ’effacer l'EEPROM depuis un OS Linux ?

En effet le tutorial [Sauvegardez et restaurez votre ZiGate](https://zigate.fr/2018/10/27/sauvegardez-et-restaurez-votre-zigate/) ne concerne que Windows.

J'ai voulu le faire sur Windows10 mais cela ne fonctionne pas avec les pilotes_PL2303.zip j'ai une erreur 10 même en suivant la procédure. 

J'ai tenté sous Linux avec https://github.com/Jerome-PS/JennicModuleProgrammer mais on ne peut pas non plus :
```
pi@raspberrypi:~/JennicModuleProgrammer $ ./Build/JennicModuleProgrammer
JennicModuleProgrammer Version: 0.6 (r56124)
Usage: ./Build/JennicModuleProgrammer
  Arguments:
    -s --serial        <serial device> Serial device for 15.4 module, e.g. /dev/tts/1
  Options:
    -V --verbosity     <verbosity>     Verbosity level. Increses amount of debug information. Default 0.
    -I --initialbaud   <rate>          Set initial baud rate
    -P --programbaud   <rate>          Set programming baud rate
    -f --firmware      <firmware>      Load module flash with the given firmware file.
    -v --verify                        Verify image. If specified, verify the image programmedwas loaded correctly.
    -m --mac           <MAC Address>   Set MAC address of device. If this is not specified, the address is read from flash.
```

Merci

**Comment by lboue** [comment]
Personne n'a trouvé de solution ou déjà rencontré ce souci ?

**Comment by ISO-B** [comment]
You can make ZiGate to clear all PDM records using command 0x0012. Alternately you can use https://github.com/tjikkun/zigate-flasher to clear eeprom and pdm.
