### ISSUE TITLE
Utiliser les "releases" github pour mettre les binaires

### ISSUE THREAD

**Issue by Salamandar** [fairecasoimeme/ZiGate#128]
Salut !
Ça n'est pas une "good practice" de mettre les binaires dans le dépôt git, même si je reconnais que c'est facile ;) . En plus, c'est difficile de s'y retrouver.
C'est plus pratique de les mettre dans les "releases" de github, visibles sous forme d'une liste avec un changelog et la liste des binaires associés bien présentés.
Il y a des outils pour automatiser l'upload des binaires, par exemple ça : https://github.com/cheton/github-release-cli

**Comment by fairecasoimeme** [comment]
Salut,
Merci pour tes conseils, je m'en occupe dès que possible.

**Comment by pipiche38** [comment]
I beleive we can close that one.
