### ISSUE TITLE
ZiGate should be transparent to Xiaomi messages 0x115F (see mail)

### ISSUE THREAD

**Issue by KiwiHC16** [fairecasoimeme/ZiGate#13]
Xiaomi Temperature Carre: zigate ne transmet pas le pacquet propriétaire de donc nous ne pouvons recevoir le niveau de batterie (Volt).

**Comment by KiwiHC16** [comment]
- Xiaomi Temperature Carre: zigate ne transmet pas le pacquet propriétaire de donc nous ne pouvons recevoir le niveau de batterie (Volt).

**Comment by zaraki673** [comment]
Bonjour,
 j'ai mis a jour mon firmware hier sur la 3.0b, pas de soucis de se genre de mon coté, 
le niveau de batterie est bien remonté sur mes capteur de temperatures (carré et rond)
pas sur les autres, mais je ne me souviens pas les avoir déja vu (ou pas vu et du coup pas codé dans mon plugin domoticz pour le coup)

**Comment by elric91** [comment]
Je confirme qu'il est également présent avec le firmware 2.x. Par contre, il n'est pas envoyé souvent

**Comment by KiwiHC16** [comment]
L'info est envoyée dans 2 types de messages. Un passe la Zigate et pas l autre. J ai envoyé à Akila une proposition de correctif.

**Comment by fairecasoimeme** [comment]
Pending for the next version
