### ISSUE TITLE
Effacer les data de la zigate

### ISSUE THREAD

**Issue by kauden** [fairecasoimeme/ZiGate#130]
Bonjour,

Est-il possible de repartir a zero avec la zigate (effacer completement les datas) ?
Je suis sur home assistant et j'ai au moins 6 modules fantôme que je n'arrive pas à supprimer. et du coup j'aimerai repartir à zero et remettre mais module un par un.

J'ai reflashé le firmware mais les datas sont toujours la.

Merci

**Comment by thierryprats** [comment]
Bonjour kauden,

Je commence tout juste avec Home Assistant et zigate, mais si je ne me trompe pas, HA a sa base de données : https://www.home-assistant.io/docs/backend/database/

Tu devrais pouvoir supprimer tes dates en utilisant avec les commandes SQLite fournies dans la documentation.

**Comment by doudz** [comment]
Il faut faire un Erase EEPROM

**Comment by kauden** [comment]
J'ai flashé la zigate sous linux et il n'y a pas d'option pour ca dans le binaire JennicModuleProgrammer.
Je vais essayer de trouver un PC sous windows pour le faire ce soir
Merci de votre retour
