### ISSUE TITLE
Probème à l'installation du Bin (lumière bleu éteinte)

### ISSUE THREAD

**Issue by pasoad** [fairecasoimeme/ZiGate#131]
Bonsoir,

Je possède une des 1ère Zigate datant du projet KickStarter, je me suis enfin décidé à passer le pas et à l'utiliser avec des produits de la gamme Ikea (oui, j'ai mis longtemps avant de commencer à l'utiliser ;) ).

J'essaye de l'installer sur Jeedom à l'aide du Plug-in "Abeille" depuis plusieurs jours mais il semblerait que le problème vienne de la clé en elle même (lien de l'issue sur le Git du Plug-in [https://github.com/KiwiHC16/Abeille/issues/562](url)).

En résumé, après le flashage à l'aide de la méthode décrite sur le site zigate.fr [https://zigate.fr/wiki/mise-a-jour-de-la-zigate/](url) ou d'après la vidéo qui m'a été partagée sur l'autre issue [https://www.youtube.com/watch?v=AWJDQpP-AF4&feature=youtu.be](url).

J'ai recommencé l’opération des dizaines de fois depuis Windows 7 et 10 et toujours rien de concluant.

Quelqu'un aurait-il une idée pour me sauver ?

Merci d'avance :)

**Comment by ISO-B** [comment]
Only situation when I have managed to get ZiGate led to be dark blue(dim) is when I plug it to usb while pressing that button.

**Comment by KiwiHC16** [comment]
Investigations I did with @pasoad : https://github.com/KiwiHC16/Abeille/issues/562

What is very strange is that we can falsh the board without error messages but when we plug it to the USB port, the ziate bleu led stay off.

**Comment by fairecasoimeme** [comment]
It's possible that is a hardware issue. Perhaps the LED is dead.

I can exchange your ZiGate. Please send me an Email at contat@zigate.fr

**Comment by pasoad** [comment]
Hi,

I can close this issue because all is working after the exchange of the zigate.

Thank you all for your help !
