### ISSUE TITLE
Réponse 0x8002 ?

### ISSUE THREAD

**Issue by doudz** [fairecasoimeme/ZiGate#133]
Dans quel cas peut-on avoir la réponse 0x8002 ? E_SL_MSG_DATA_INDICATION
J'ai l'impression que cela permet d'avoir des données brut mais je ne reçois jamais cette réponse
Cela pourrait être intéressant dans le cadre de l'intégration avec zigpy

**Comment by fairecasoimeme** [comment]
Je me trompe peut-être mais c'est une commande interne à la stack ZigBee. Ce n'est pas une réponse radio classique

Je pense qu'il faut regarder du côté de la commande E_SL_MSG_SEND_RAW_APS_DATA_PACKET pour envoyer de commandes brutes.

Pour ce qui est de recevoir des données brutes, par contre, il faut creuser mais peut-être qu'il n'y a pas beaucoup à changer dans le firmware...

**Comment by doudz** [comment]
Pour E_SL_MSG_SEND_RAW_APS_DATA_PACKET effectivement c'est la bonne commande.
Concernant la réception il faut que je creuse encore un peu mais s'il s'avère que la réception de donnée brut est nécessaire, on pourrait imaginer une option à activer pour permettre à la zigate de passer en "mode données brutes"

**Comment by pipiche38** [comment]
#307

**Comment by pipiche38** [comment]
implemented in 31d. All messages not processed by the firmware will be reported as 0x8002
