### ISSUE TITLE
After upgrading to 3.0f I can't pair my Hue bulbs again. 

### ISSUE THREAD

**Issue by santricity** [fairecasoimeme/ZiGate#143]
Hi,
I just upgraded firmware to 3.0f, all devices (ikea bulbs, aqara pirs, osram) paired successfully except Philips Hue bulbs. I don't have Philips remote to force them into pairing mode. Is there any way to make them working with Zigate again? I'm running on stable latest Zigate Plugin, Domoticz 4.9700 on up to date Raspbian.

**Comment by santricity** [comment]
Should I really buy Hue Remote to make it working again?

**Comment by doudz** [comment]
I'm not sure but maybe you could use the commande 0x00D2 "Touch link factory reset target" ? Because I suppose that's the HUE remote is doing
if someone could confirm

**Comment by santricity** [comment]
Thank you! Could you let me know how to send this command to the device?

**Comment by doudz** [comment]
Don't know using Domoticz, so probably with ZGUi

**Comment by santricity** [comment]
Could you let me know how I can send this command through the ZGUI? I installed it, connected the USB ZiGate stick, I can discover some devices, but I don't know where I should put this command. Too many options and fields...

**Comment by pipiche38** [comment]
@fairecasoimeme is there any specific condition to do the Factory reset Touch Link ? Is this really reseting the Hub Bulb and make them able to re-pair ?

**Comment by santricity** [comment]
Fixed by ordering Hue dimmer remote.

**Comment by sifus** [comment]
hi, what is the adress to the 3.0f Bin ?

**Comment by pipiche38** [comment]
@sifus : https://github.com/fairecasoimeme/ZiGate/releases

**Comment by sifus** [comment]
Sorry, i try to get this bin with linux command :
./JennicModuleProgrammer -V 6 -P 115200 -f « < ??? > » -s /dev/ttyUSB1

**Comment by pipiche38** [comment]
I think this can be closed !
