### ISSUE TITLE
Documentation: Update link to download Firmware

### ISSUE THREAD

**Issue by waltervl** [fairecasoimeme/ZiGate#154]
In the documentation on page https://zigate.fr/wiki/mise-a-jour-de-la-zigate/ there is a link to download firmware  (Télécharger le Firmware du module radio) but it goes to the wrong direction.

Please have it link to https://github.com/fairecasoimeme/ZiGate/releases/tag/Release instead of the one that is used now (https://github.com/fairecasoimeme/ZiGate/tree/master/Module%20Radio/Firmware).
I have been searching for the 30f bin for a long time....

**Comment by fairecasoimeme** [comment]
Sorry, It's right, I'll update.

Thanks for information
