### ISSUE TITLE
Firmaware 3.0f - Ikea Tradfri

### ISSUE THREAD

**Issue by battousai90** [fairecasoimeme/ZiGate#155]
Hello,

Since the frimware upgrade to 3.0f, the temperature control of my Ikea Tradfri don't work.

**Comment by fairecasoimeme** [comment]
Hi,
we did not make any changes on that part. Are you sure this is the only modification ? no plugin update ? no other manipulations ?

**Comment by battousai90** [comment]
Hello,

Only flash for firmware 3.0f, so of course eeprom erase and include all device.
Before i was on Jeedom with Plugin 1.2.2 and firmware 3.0f, and no problem, all was perfect. Jeedom send me notification for said that Zigate firmware is outdated, so i checked for upgrade it.
After the flash to 3.0f, i still on Jeedom with plug-in 1.2.2, saw all device but nothing work, after an erase PDM all device was disappaired. Include all again,but Tradfri not have Temperature control, i have the slider, but nothing happen when move it.

**Comment by battousai90** [comment]
After some test, the problem is the plugin Zigate 1.2.2, because with the plug-in Abeille, temperature controle on IKEA tradfri works perfectly.

**Comment by doudz** [comment]
There was a bug in version 1.2.* of the Jeedom plugin. It has just been fixed and it should be ok in the next 1.2.3 release

**Comment by battousai90** [comment]
Ok thank you very much Doudz. Waiting on 1.2.3.
