### ISSUE TITLE
Strange xiaomi reaction

### ISSUE THREAD

**Issue by max5962** [fairecasoimeme/ZiGate#158]
Hello, bonjour,

Yesteday, i experiencing some strange xiaomi behavior.
My motion sensor stop reporting their state '2019-02-20 21:33:51' and was suddenly blinking.
In log it seem that zigate received announce.
Is that normal ?
 
[Log.log](https://github.com/fairecasoimeme/ZiGate/files/2889883/announce.log)

**Comment by pipiche38** [comment]
Yes, that is a normal behaviour of the Xiaomi devices , where for different reason they could re-issue a device announcement even if they are already paired.
With this device announcement they will most-likely come with a new network ID (short address)
