### ISSUE TITLE
Zigate doc and 0x8000 message

### ISSUE THREAD

**Issue by pipiche38** [fairecasoimeme/ZiGate#163]
In Zigate.fr for the description of Réponse 0x8000, I see that there is an Optional additional error information (as a string).

Could you kindly clarify what should we expect here ?

**Comment by ISO-B** [comment]
I took quick look on source and couldn't find any instance where 0x8000 would return anything else than status, sequence number and packet type. Unless there is internal commands that we can't see. 

@fairecasoimeme do you know for sure that there is case where it will output optional error information or is this just for future proofing?

**Comment by pipiche38** [comment]
Obj -> ZiGate | 0x8000 | Status | <status:uint8_t> | All status messages will have a sequence number sent back. Default of 0 for messages which are not transmitted over the air.
-- | -- | -- | -- | --
  |   |   | <sequence number: uint8_t> |  
  |   |   | <Packet Type: uint16_t> |  
  |   |   | <Optional additional error information: string>

**Comment by fairecasoimeme** [comment]
I copied informations from JN-AN-1216-ZigBee-3-0-IoT-ControlBridge-UserGuide.pdf
But, It's true, I never seen Option all error information yet.

**Comment by ISO-B** [comment]
Maybe it is there so users could implement their own additional error information. Remove it from documentation for now and add back if it becomes useful?

**Comment by fairecasoimeme** [comment]
Updated
