### ISSUE TITLE
Can I get binary for JN5169?

### ISSUE THREAD

**Issue by seyriz** [fairecasoimeme/ZiGate#17]
Hi, I want to build a Zigbee Gateway for my house.
But I have only JN5169 module.
If you not want open source code, could you build binary for JN5169?

**Comment by fairecasoimeme** [comment]
I'll try to give this next week.

**Comment by dystopy** [comment]
Hi, would be great to get binary for 5169 !

**Comment by intra-au** [comment]
Please, create a binary for 5169! Thanks from Australia 👍

**Comment by michael067** [comment]
+1, can you create a binary for JN5169.
Thanks

**Comment by michael067** [comment]
someone as successfully compiled for a jn5169 ?

**Comment by fairecasoimeme** [comment]
Hi,
you can find here : 
[https://github.com/fairecasoimeme/ZiGate/tree/master/Module%20Radio/Firmware/bin/ZiGate/JN5169](https://github.com/fairecasoimeme/ZiGate/tree/master/Module%20Radio/Firmware/bin/ZiGate/JN5169)

**Comment by michael067** [comment]
Thanks, it's good :-) it's a 3.0f version.
i start test with zigate
