### ISSUE TITLE
Doc error for response 0x8002

### ISSUE THREAD

**Issue by doudz** [fairecasoimeme/ZiGate#178]
There's an error in doc for the response 0x8002, there's no payload size in response (and this is not needed)

Arguments are :

status: uint8_t
Profile ID: uint16_t
cluster ID: uint16_t
source endpoint: uint8_t
estination endpoint: uint8_t
source address mode: uint8_t
source address: uint16_t or uint64_t
destination address mode: uint8_t
destination address: uint16_t or uint64_t
~~payload size : uint8_t~~
payload : data each element is uint8_t

**Comment by touzi95** [comment]
hey, can i have you LinkedIn /facebook/email i want to contact you. 
Thank you.

**Comment by fairecasoimeme** [comment]
fixed
