### ISSUE TITLE
Error in wiki

### ISSUE THREAD

**Issue by gotakk** [fairecasoimeme/ZiGate#193]
Hello,

I just found a little error on the wiki.
Simple Descriptor Request command is 0x0043 and not 0x0045
<img width="341" alt="Capture" src="https://user-images.githubusercontent.com/866538/57123383-de579000-6d81-11e9-93d7-2b5869904877.PNG">

Thanks

**Comment by pipiche38** [comment]
You are right.
Here is the reference list: https://zigate.fr/wiki/commandes-zigate/

**Comment by fairecasoimeme** [comment]
oups :) 
Sorry. Fixed.
Fred
