### ISSUE TITLE
Wrong decoding of INNR Remote ( 0x8085 doesn't report the reallity )

### ISSUE THREAD

**Issue by pipiche38** [fairecasoimeme/ZiGate#194]
It seems that there is some descrapancy in the way the Zigate is decoding and providing information to the 0x8085 message with the INNR RC110 remote controller

the Left/Right button are always providing the same infos, while when sniffing the messages with Ubiqua we see the right things

With Ubiqua, we see
Level Control: Move Up , Move Down, Stop

with Zigate, we see only Release Down, Stop

**Comment by pipiche38** [comment]
![Capture-move-down](https://user-images.githubusercontent.com/8291674/57139822-82f3c500-6db6-11e9-9b5e-d955adc2b549.PNG)

**Comment by pipiche38** [comment]
![Capture-move-up](https://user-images.githubusercontent.com/8291674/57139839-88510f80-6db6-11e9-8ae0-fa4b7178cfeb.PNG)

**Comment by fairecasoimeme** [comment]
Normally fixed in v3.1a

**Comment by pipiche38** [comment]
Thanks , it works !
