### ISSUE TITLE
Message 0x804E should also have Source Address

### ISSUE THREAD

**Issue by pipiche38** [fairecasoimeme/ZiGate#198]
When you send a message 0x004E, you expect to have a 0x804E, however there is no source address in the 0x804E.

Would be great to have such information as for the other messages !

**Comment by fairecasoimeme** [comment]
Hi,
I don't really understand by source address because, you normally get each source address from neighbor like this (for example) :

Type: 0x804E (Mgmt LQI Response)
  SQN: 0x68
  Status: 0x00
  Nb Table Entries: 2
  Start Index: 0
  Nb Table List Count: 2
  Neighbor 0:
    Extended Pan ID: 0xEE81BB144F75C53C
    Extended Address: 0x158D0001C5D10F
    Nwk Address: 0x0000
    LQI: 255
    Depth: 0
    Flags: 0x48
    Device Type: Coordinator
    Permit Joining: Unknown
    Relationship: Parent
    RxOnWhenIdle: Yes
  Neighbor 1:
    Extended Pan ID: 0xEE81BB144F75C53C
    Extended Address: 0xB57FFFE3686DA
    Nwk Address: 0x09A3
    LQI: 255
    Depth: 2
    Flags: 0x12
    Device Type: End Device
    Permit Joining: Off
    Relationship: Child
    RxOnWhenIdle: No

Could you precise ?
Fred

**Comment by pipiche38** [comment]
By Source address I'm talking about from which router this List of neighbours is sent !
The Nwk Address that are listed here are the neighbours of this "Source Address"

**Comment by fairecasoimeme** [comment]
source address added to v3.1a

**Comment by pipiche38** [comment]
Excellent, will make the things much reliable

**Comment by pipiche38** [comment]
Merci

**Comment by doudz** [comment]
Doc not up to date

**Comment by fairecasoimeme** [comment]
For me, It's up to date. What informations is missing ?

**Comment by pipiche38** [comment]
Fixed 3.1a
