### ISSUE TITLE
zigate source code availability (firmware nxp5168)

### ISSUE THREAD

**Issue by gbrd** [fairecasoimeme/ZiGate#2]
Hi, 
Are there any plans to share the firmware code of zigate in this repository  ? (firmware for nxp 5168)

**Comment by loicortola** [comment]
+1 . I am willing to contribute and spend some time on improving some Zigate code as long as it is OpenSource :)

**Comment by gbrd** [comment]
no answer ? :)

**Comment by handfreezer** [comment]
+1

**Comment by snowshow** [comment]
+1

**Comment by fairecasoimeme** [comment]
I'm waiting to deliver a good version with some clean debug
It's for soon

**Comment by lolorc** [comment]
Any news ?
by the way, why would you close issues before fixing them ? ;-)

**Comment by intra-au** [comment]
I have few spare nxp5169 modules and would like to contribute too, however with 5169 binary not released and 5168 source not provided I'll probably end up making my own firmware from scratch using your protocol for compatibility with other modules

**Comment by lolorc** [comment]
@intra-au @fairecasoimeme 
might be useful to re-open this issue or create another one.
That would be sad and a waste of time to start from scratch.

**Comment by intra-au** [comment]
@fairecasoimeme any chance it can be done soon?

**Comment by fairecasoimeme** [comment]
yep, soon... with the new firmware 3.0e

**Comment by pdecat** [comment]
Any idea of the license terms under which the source code will be distributed?

**Comment by pipiche38** [comment]
Suggest to close that one.
NXP code is provided as per NXP Copyright

Proper LIcense will be specify for this project
