### ISSUE TITLE
0x804A should report Source address

### ISSUE THREAD

**Issue by pipiche38** [fairecasoimeme/ZiGate#203]
The 0x804A should report the source address

**Comment by fairecasoimeme** [comment]
Added to v3.1a

**Comment by pipiche38** [comment]
Merci

**Comment by doudz** [comment]
Doc not up to date

**Comment by fairecasoimeme** [comment]
For me, It's up to date. What informations is missing ?

**Comment by doudz** [comment]
I'm using https://zigate.fr/wiki/commandes-zigate/ as doc and for 0x804A I don't see the source address

**Comment by fairecasoimeme** [comment]
It's an old link.
You have use this :[https://zigate.fr/documentation/commandes-zigate/]( https://zigate.fr/documentation/commandes-zigate/)
Fred

**Comment by doudz** [comment]
Oh... OK sorry
Thank you :)
