### ISSUE TITLE
0x8101 - missing Source Address

### ISSUE THREAD

**Issue by pipiche38** [fairecasoimeme/ZiGate#210]
In message 0x8101 there is the SourceEP and ClusterID but no reference to Source Addr.

**Comment by ISO-B** [comment]
It is missing source address because those responses are only written when ZiGate processes command sent by you. If you have use case where it would be usefully it can be easily added. I wouldn't add it just for getting arbitrary source address.

**Comment by pipiche38** [comment]
This the case with Pluzzy device and especially the door contact which use 0x8101 to send Open /Close status

Envoyé de mon iPhone

**Comment by pipiche38** [comment]
https://github.com/fairecasoimeme/ZiGate_HA1.2/issues/1

**Comment by pipiche38** [comment]
https://github.com/sasu-drooz/Domoticz-Zigate/issues/429
