### ISSUE TITLE
AttributeDiscoveryResponse and complete status

### ISSUE THREAD

**Issue by bghes** [fairecasoimeme/ZiGate#212]
AttributeDiscoveryResponse always send complete 1 which not permit to get the end of the attribute list.
Is-it a bug ?

**Comment by ISO-B** [comment]
I can take a look. Could you provide logs?

**Comment by pipiche38** [comment]
@bghes It might be good that you provide also information on the Firmware Version.
I'm using this feature and never see any issue ! Can it be linked to the device itself ?

**Comment by bghes** [comment]
Hello,
I use the last firmware 3.1a with a driver i have developped. 
In the log i print the complete status of each attribute discovery response.
[trace-2.txt](https://github.com/fairecasoimeme/ZiGate/files/3438265/trace-2.txt)
[trace.txt](https://github.com/fairecasoimeme/ZiGate/files/3438249/trace.txt)

Thanks

**Comment by pipiche38** [comment]
On my case I'm not using this flag. I'm collecting all Attribute discovery responses to construct the full list of Cluster Attribute for the particular device.

I'm doing that , most-likely because indeed the flag is always set to 1 ;-)

**Comment by pipiche38** [comment]
I do confirm that the Flag seems to be alway set to 1.
From what I saw in the code, it is just passing the flag from the Zigbee stack.

So I would recommend you not to take the flag in consideration, but more to compile every attribute you receive.

**Comment by pipiche38** [comment]
Closed as a feature
