### ISSUE TITLE
Trigger 0x8024 message

### ISSUE THREAD

**Issue by KiwiHC16** [fairecasoimeme/ZiGate#22]
Message 0x8024 is triggered when we send a message 0x0024 to Zigate.
Once Zigate receive 0x0024 message it starts the network. If we unplug/replug the zigate the network will start automatically. 
If we send 0x0024 again, the zigate do not reply with 0x8024 anymore.

How can we get/trigger 0x8024 message ?
Perhaps there is a similar mesage but I can't find it.

**Comment by fairecasoimeme** [comment]
Fixed with version 3.0d. You have to execute 0x0009 command to get Network State
