### ISSUE TITLE
Konke Motion integration

### ISSUE THREAD

**Issue by pipiche38** [fairecasoimeme/ZiGate#220]
There is a strange behaviour of the Konke Motion which is on a regular basis is sending a 0x8102 Individual Attribute response and in such is creating a False Positive as the Alarm1 is set to 1.

**Comment by pipiche38** [comment]
Every 15' 
2 times 0x8102
2 times 0x8401

**Comment by pipiche38** [comment]
I would like also to confirm that Enrollement is also made, and I got that confirmation also every 15' !

**Comment by fairecasoimeme** [comment]
I test my motion sensor on my ZiGate and I come back to you to tell my results

**Comment by fairecasoimeme** [comment]
I test my device but I didn't reproduce the issue.

My sensor send only when it detects moves. only 1x 0x8401

Could you test directly with ZWGUI ?

Fred.

**Comment by pipiche38** [comment]
Will do and revert

**Comment by pipiche38** [comment]
Ci-joint le problème avec ZGUI

Trames reçues à 15:56, 16:04, 16:20 alors que le Motion sensor est dans sa boite dans une armoire
 
![image](https://user-images.githubusercontent.com/8291674/62785918-dbc3af80-bac1-11e9-9505-3ba4ecc6ccb1.png)

**Comment by fairecasoimeme** [comment]
C'est vraiment bizarre, je n'ai pas du tout ça de mon côté.
Tu as quelle version de firmware ? la v3.1a ?

**Comment by pipiche38** [comment]
Oui, je vais regarder de plus pret la phase d'appairage et notamment il y a des bindings qui sont fait et un configureReporting, qui peuvent peut-etre agir :-(

Je cherche de mon coté et je te dis quoi ;-)

**Comment by fairecasoimeme** [comment]
A oui s'il y a des bindings, c'est surement ça.

**Comment by pipiche38** [comment]
Je ferme l'issue, désolé j'aurai du poussé les tests un peu plus loin.
Le problème semble etre lié au Binding/Configure Reporting
