### ISSUE TITLE
Attribute Reporting does not work for data larger than uint8.

### ISSUE THREAD

**Issue by schrodingersket** [fairecasoimeme/ZiGate#223]
Attribute Reports and Attribute Reads do not correctly send data that is larger than a uint8 (e.g., when reading power metering data) due to a failure to increment a pointer reference when reading attributes.

Pull request incoming with a fix.

**Comment by pipiche38** [comment]
Could you please give a precise example as I didn't have any issue with Configure Reporting nor read attribute, and I'm getting Instant Power measurement with devices which are reporting with 24bits and 48bits unsigned integer datas

**Comment by pipiche38** [comment]
For having tested 3.1b I do confirm that uint48 is now correctly received from Zigate to API

**Comment by pipiche38** [comment]
should be close!
