### ISSUE TITLE
0x8024 with status 6 ?

### ISSUE THREAD

**Issue by doudz** [fairecasoimeme/ZiGate#225]
A user report a problem ,0x8024 return status 6, what does it mean ?

**Comment by pipiche38** [comment]
From what I saw in the Source,

0x0024 --> APP_vControlNodeStartNetwork --> BDB_eNfStartNwkFormation()

BDB_E_ERROR_COMMISSIONING_IN_PROGRESS

@fairecasoimeme to confirm

**Comment by doudz** [comment]
Hum, and what should we do? Just wait a little and retry command 0x0024?

**Comment by ISO-B** [comment]
Is user trying to start network as coordinator not end device or router? Is this after fresh install?

**Comment by doudz** [comment]
The user got that on first start after upgrading to 3.1a

**Comment by pipiche38** [comment]
@doudz, this message is indeed coming from 3.1a, where 0x8024 messages have been normalized (see #74) .

0x06: Commissioning in progress. If network forming is already in progress

For the meaning, may be @fairecasoimeme can comment
