### ISSUE TITLE
How to use 0x0530 - APS Raw

### ISSUE THREAD

**Issue by pipiche38** [fairecasoimeme/ZiGate#226]
I'm looking for information on how to use the 0x0530, and especially to understand the structure of the Data we have to pass. Is there any pointers somewhere ?

Thanks

**Comment by ISO-B** [comment]
It is most general transfer function, which accepts everything. It basically uses ZPS_eAplAfApsdeDataReq function more information about that can be found from JN-UG-3101 v1.5 page 176.

**Comment by pipiche38** [comment]
Thanks, that is indeed what I found, but hen the question is about 
PDUM_thAPduInstance

for which I didn’t find any structure information.


Kind regards
