### ISSUE TITLE
0x8120 do not reporting the right Attribute

### ISSUE THREAD

**Issue by pipiche38** [fairecasoimeme/ZiGate#234]
0x8120 as per documentation is:

<img width="907" alt="Screenshot 2019-09-01 at 14 51 31" src="https://user-images.githubusercontent.com/8291674/64076680-058a8380-ccc8-11e9-8fdc-026f3c9fd6f5.png">

However it looks like it is always sending back 1 and only one attribute and always '0000'

**Comment by badzz** [comment]
https://github.com/fairecasoimeme/ZiGate/pull/309

**Comment by pipiche38** [comment]
Fixed in 31d
