### ISSUE TITLE
Error connect Zigate portcom

### ISSUE THREAD

**Issue by minhtan58** [fairecasoimeme/ZiGate#237]
Hi everyone
I get a problem When I build ZiGate v3.1a (final) project.
Use Zigate from https://pypi.org/project/zigate/ to connect to Coordinator,

Use ZiGate_coordinator_JN5169.bin (in forder bin) it connect ok.
Build JN5169-115200
https://user-images.githubusercontent.com/34535797/64834116-d3075180-d60a-11e9-8e56-b740595e46d9.png
=> I can't open port to connect Coordinator
Can you help me? I don't know what is reason !!!

**Comment by minhtan58** [comment]
![image](https://user-images.githubusercontent.com/34535797/64932530-ea904580-d869-11e9-97d7-7ad861d19a80.png)

![image](https://user-images.githubusercontent.com/34535797/64932527-d51b1b80-d869-11e9-99e1-45351662fb32.png)

**Comment by doudz** [comment]
What was the problem ?
