### ISSUE TITLE
ZPS_EVENT_APS_DATA_CONFIRM only forwarded in case of failure

### ISSUE THREAD

**Issue by doudz** [fairecasoimeme/ZiGate#239]
Currently ZPS_EVENT_APS_DATA_CONFIRM is only forwarded in case of failure using 0x8702 E_SL_MSG_APS_DATA_CONFIRM_FAILED

Using the raw mode (with zigpy) it could be very useful to have success too, not only failure.

https://github.com/fairecasoimeme/ZiGate/blob/master/Module%20Radio/Firmware/src/ZiGate/Source/ZigbeeNodeControlBridge/app_zcl_event_handler.c#L251-L276

**Comment by pipiche38** [comment]
My understanding is that is in the pipe for 3.1b

**Comment by fairecasoimeme** [comment]
I confirm. It will be in v3.1b version

**Comment by pipiche38** [comment]
Should be closed
