### ISSUE TITLE
Erasing eeprom issues?

### ISSUE THREAD

**Issue by petruskevicius** [fairecasoimeme/ZiGate#24]
Whenever I try to erase EEPROM memory with NXP Programmer, I receive such error:
![image](https://user-images.githubusercontent.com/7474577/36343564-64dbce64-1416-11e8-8fbd-aadfec27d497.png)

**Comment by fairecasoimeme** [comment]
New upload here.
https://github.com/fairecasoimeme/ZiGate/blob/master/Tools/FlashProgrammer/flashprogrammer.zip
