### ISSUE TITLE
Question: Configure reporting on Philips Hue bulbs

### ISSUE THREAD

**Issue by pipiche38** [fairecasoimeme/ZiGate#240]
Can you confirm or not that Configure Reporting works with Philips Hue ? Or there is a need to get a pooling in place to collect their status

Thanks in advance

**Comment by Smanar** [comment]
From my last informations , Philips don't use Reporting, it spam  request over the network fastest it can.

**Comment by pipiche38** [comment]
> 
> 
> From my last informations , Philips don't use Reporting, it spam requests over the network fastest it can.

so polling is the way to do !

**Comment by fairecasoimeme** [comment]
I confirm :(

**Comment by pipiche38** [comment]
merci à tous les deux
