### ISSUE TITLE
Zigate Box 3D Model

### ISSUE THREAD

**Issue by ruimarinho** [fairecasoimeme/ZiGate#241]
Hi @fairecasoimeme,

I have bought the new TTL module and as you mentioned, the plastic enclosure is slightly bigger than it should.

I have a friend who can do the 3D printing for me of an adjusted enclosure. Would you mind sharing the model with the community?

Thank you,

**Comment by fairecasoimeme** [comment]
Hi,
you can find here
https://www.hammfg.com/fr/part/search?filter%5Bq%5D=1551USB3

fred

**Comment by pipiche38** [comment]
can be close

**Comment by ruimarinho** [comment]
Indeed! Thank you @fairecasoimeme. First prototype last week is looking nice :) it offers a much better fit with only 3mm less in length!


![IMG_1097](https://user-images.githubusercontent.com/288709/69893623-2f296a00-130c-11ea-8f3b-b9d8a1b7c54e.jpg)
![IMG_3095](https://user-images.githubusercontent.com/288709/69893624-2f296a00-130c-11ea-92a0-0cd722177b81.jpg)
![IMG_3190](https://user-images.githubusercontent.com/288709/69893625-2f296a00-130c-11ea-921f-6549f3e8369e.jpg)

**Comment by doudz** [comment]
I'm going to print a new box too to with a button to be able to use the flash mode without disassembling the box
