### ISSUE TITLE
Device Annouced: Join versus Rejoin

### ISSUE THREAD

**Issue by pipiche38** [fairecasoimeme/ZiGate#247]
In there attached traces, there is a Rejoin Request at Zigbee protocol. Would it be possible to enhanced Device Annouced 0x004D in order to have the Flag Rejoin True or False ?

![Capture](https://user-images.githubusercontent.com/8291674/66702596-90b85980-ed09-11e9-9e79-e82e384b1cc2.PNG)

**Comment by fairecasoimeme** [comment]
I added the rejoin information to the packet "0x004D" at the end.
It will be avalaible in v3.1b.

**Comment by pipiche38** [comment]
merci!
