### ISSUE TITLE
Support  SONOFF BASICZBR3

### ISSUE THREAD

**Issue by M4t3o** [fairecasoimeme/ZiGate#250]
Hi 

just for informations, i've just seen that sonoff distributes a zigbee component :
https://www.itead.cc/sonoff-basiczbr3.html

I'd like to try this one with my zigate when it could be possible.
I don't find it here : https://zigate.fr/le-materiel-compatible-zigate/

Have u plan to support it ?

Regards.

**Comment by pipiche38** [comment]
SONOFF devices are usually well compatible with Zigate, I wouldn't see any reason why it wouldn't be the case here.
They mention that it works with SmartThings hub, so that is quiet positive.

I don't know why application and plugin your are using, but if you are based on Domoticz and the Zigate plugin, I would be more than happy to help you in case of trouble.

**Comment by pdecat** [comment]
Isn't the BASICZBR3 the first SONOFF device using the Zigbee protocol?
AFAICT, that's the only one listed on [their Zigbee website](https://sonoff.tech/product/zigbee-diy-smart-switches/basiczbr3).

**Comment by pipiche38** [comment]
that is indeed this one

**Comment by fairecasoimeme** [comment]
I will order and I'll tell you ;)
Fred

**Comment by pipiche38** [comment]
As mentioned in my early comment, indeed it is a supported one and works well with Zigate (and the Domoticz plugin)

**Comment by Hedda** [comment]
FYI, SONOFF BASICZBR3 is based on Texas Instruments CC2530 with Z-Stack Home 1.2 firmware with switch/router config and should use the Zigbee Home Automation (HA) application profile specification. For some more information see https://github.com/Koenkk/Z-Stack-firmware/issues/145 and https://github.com/Koenkk/Z-Stack-firmware/issues/153 as well as https://notenoughtech.com/home-automation/sonoff-basic-r3-zigbee/

**Comment by pipiche38** [comment]
It is supported ... 
https://zigate.fr/produits-sonoff-compatible-zigate/

tobe closed
