### ISSUE TITLE
How to address an End-Terminal in a group.

### ISSUE THREAD

**Issue by KiwiHC16** [fairecasoimeme/ZiGate#260]
Zigate use different mode to address device(s).
Bound = 00
Group = 01
Short = 02
Broadcast = 0x
etc
But if you put Group the NWK address used is 0xFFFD and not 0xFFFF eating that only routeurs are addressed (MAC Dest Addr is 0xFFFF).

If you use Broadcast, then NWK address is 0xFFFF but then the group destination is not used. So all equipments receive the message.

The expected MAC Dest (0xFFFF) - NWK (0xFFFF) - Group (0xXXXX)
We can get :
MAC Dest (0xFFFF) - NWK (0xFFFD) - Group (0xXXXX)
or
MAC Dest (0xFFFF) - NWK (0xFFFF)

**Comment by pipiche38** [comment]
I'm not sure to understand the point or question.

When you use Group Mode ( as addressing mode) you use a total different address range, so there is no mix between Network address and Group address.
