### ISSUE TITLE
Flow control RTS/CTS

### ISSUE THREAD

**Issue by doudz** [fairecasoimeme/ZiGate#261]
The firmware 3.1a is supposed to have Flow control RTS/CTS but I don't see anything related in doc
is it working ?
how it works ?

**Comment by pipiche38** [comment]
What I undertsood is that is related to new upcoming Zigate. But @fairecasoimeme would say more

**Comment by fairecasoimeme** [comment]
Yep, normally that's ok but you have to get the last hardware (there are new pin RTS/CTS but without header). I added this function to anticipate the future hardware.

**Comment by doudz** [comment]
ok, so there's nothing to do on my side ;)
