### ISSUE TITLE
Déconnexions et erreurs diverses

### ISSUE THREAD

**Issue by Kenderv** [fairecasoimeme/ZiGate#266]
Bonjour,
J'ai beaucoup de déconnexions et d'erreurs dans les logs de mon plugin zigate. 
Peux-tu, stp, jeter un œil sur les échanges que j'ai avec @doudz à ce propos. Voici le lien de nos échanges : https://github.com/jeedom-zigate/jeedom-plugin-zigate/issues/233 
Serait-il possible de changer de pilote (s'il est en cause) et si oui comment faire ?
Merci de ton aide

**Comment by fairecasoimeme** [comment]
Bonjour,
contacte moi par mail à l'adresse contact[at]zigate.fr avec ton numéro de commande.
Fred

**Comment by Kenderv** [comment]
Merci pour ton aide et ton professionnalisme. 
Jean
