### ISSUE TITLE
MQTT Problem

### ISSUE THREAD

**Issue by jelev** [fairecasoimeme/ZiGate#269]
Hi,

I have a new ZiGate-WiFi and it's working with HA via WiFi and USB, but I can not get it work with MQTT. It connects to MQTT server and send status but nothing from devices did not post.
My version is  `ZiGate-WiFi` v2.00 with esp-link v3.2.50-gfe4f565-dirty` 
Please, if anyone had same issue resolved, to give me advice.

**Comment by pipiche38** [comment]
Shouldn't you post this issue on the HA GitHub/Forum ?
This GitHub is for Zigate firmware related issues

**Comment by pipiche38** [comment]
to be closed
