### ISSUE TITLE
support clearing EEPROM/PDM from linux with JennicModuleProgrammer

### ISSUE THREAD

**Issue by lolorc** [fairecasoimeme/ZiGate#27]
subject says it all :-)

**Comment by tjikkun** [comment]
Well, I think it is better that the Zigate firmware keeps an application version, and clears structures when needed.

**Comment by ISO-B** [comment]
You can make ZiGate to clear all PDM records using command 0x0012. Alternately you can use https://github.com/tjikkun/zigate-flasher to clear eeprom and pdm.

Next release version should be able to automatically migrate to next version even if there is changes in structures. More information can be found from #141 and #166

**Comment by doudz** [comment]
For record, https://github.com/tjikkun/zigate-flasher doesn't support erase, the function is buggy
