### ISSUE TITLE
IASACE problem !!!

### ISSUE THREAD

**Issue by minhtan58** [fairecasoimeme/ZiGate#270]
Hi. 
I just adding ACE cluster to Zigate:
1.zcl_options.h
       #define CLD_IASACE
       #define IASACE_SERVER
2. modify .zpscfg
![image](https://user-images.githubusercontent.com/34535797/71759323-19482f80-2ede-11ea-9a7f-9ed6a22d7dd9.png)
3. Modify in SDK : Add to struct in control_bridge.h, .c
![image](https://user-images.githubusercontent.com/34535797/71759359-92e01d80-2ede-11ea-92dc-2c052688c04c.png)
But Program is crash when i start it
![image](https://user-images.githubusercontent.com/34535797/71759395-fc602c00-2ede-11ea-8652-bdce2b6f23ef.png)
By the way, When i run with Origin SW from NXP it work well.
Happy new year!!!

**Comment by pipiche38** [comment]
Would be interested to know for which device you want to have IASACE enabled ?

**Comment by minhtan58** [comment]
thank for reply. I run Zigate sw on JN5169
for control IAS WD, I use button from I-horn sen request to Coodinator. 
I use JN-AN-1201 as advice.

**Comment by pipiche38** [comment]
So why not using  cluster  0X0502 instead ? this will do the same and is implemented in Firmware 3.1a

**Comment by minhtan58** [comment]
Thanks you! But now i want add IAS ACE to Zigate for more opiton control! 
I don't know, my sw isn't work when i define ACE cluster
Have nice day!!!

**Comment by pipiche38** [comment]
As you want. My understanding is that Zigate is under memory pressure and adding one more cluster server could be challenging.

Enjoy

Envoyé de mon iPhone

**Comment by minhtan58** [comment]
Yes! I thing so. Is there any way to fix that? Thanks

**Comment by pipiche38** [comment]
This will be addressed by some of the PR targeted for 31d.

In between if you have commands to be send from Controler to Devices, you can use the 0x0530 (raw mode) command to issuse then. In 31d you'll get upcoming unmanaged clusters via 0x8002
