### ISSUE TITLE
IKEA Tardif télécommande : Pas de commandes

### ISSUE THREAD

**Issue by sifus** [fairecasoimeme/ZiGate#277]
Hello,

les commandes ne remontent pas lors de l'association avec la télécommande tardif d'Ikea ni le type d'appareil.

<img width="1679" alt="Capture d’écran 2020-02-11 à 11 02 57" src="https://user-images.githubusercontent.com/2979258/74227110-15b67e00-4cbe-11ea-818c-9bb4b24565cf.png">

**Comment by pipiche38** [comment]
please do check with Jeedom plugin developper.
Issue should be close

**Comment by sifus** [comment]
hi, what is "check" ?

**Comment by pipiche38** [comment]
> hi, what is "check" ?

ask the Jeedom plugin developpers

**Comment by pipiche38** [comment]
shoudl be close
