### ISSUE TITLE
Flashing time?

### ISSUE THREAD

**Issue by petruskevicius** [fairecasoimeme/ZiGate#28]
With every single attempt to flash Zigate into new firmware it gets harder and harder to do that. First of all flashing time started to increase. Currently it takes 2 hours to flash the firmware and ~30 minutes to verify blocks. However, normally I need to flash firmware several times because after 1st/2nd attempt I get ~1500 errors in data verification

**Comment by fairecasoimeme** [comment]
Hi, 
Normally, less than 1 minute is necessary to flash firmware. Try to decrease baudrate to 115200 bauds to flash.
