### ISSUE TITLE
Compatibility with XIAOMI MIjia Light sensor

### ISSUE THREAD

**Issue by gdseb** [fairecasoimeme/ZiGate#289]
Brand | Xiaomi MIjia
Model | GZCGQ01LM

The inclusion of the material is ok but the information feedback (luminosity) does not work.

In the logs of the zigate plugin, I have the following errors:
[2020-04-28 13:38:49][INFO][zigate](ZiGate-Decode data) : No template found for lumi.sen_ill.mgl01
[2020-04-28 13:38:49][ERROR][zigate](ZiGate-Decode data) : Command 0x0140 failed E_ZCL_ERR_ZTRANSMIT_FAIL : b''
[2020-04-28 13:39:12][WARNING][zigate](ZiGate-Decode data) : Unknown response 0x8035

Version plugin 1.6.4
Version lib 0.38.6
Version firmware 3.1c
Port : ZiGate

**Comment by fairecasoimeme** [comment]
Hi,
I think you have to ask the plugin developper. 
Fred

**Comment by pipiche38** [comment]
It works on Domoticz, but you need to bind the Cluster in order to get the infor (which is not the case for the previous LUMI devices)

**Comment by gdseb** [comment]
OK. Thanks for your reply but i am on Jeedom V4

**Comment by tcharp38** [comment]
@gdseb 
This sensor is known to be badly supported by Jeedom but there is some work ongoing.
Anyway, you should use Jeedom issues and not Zigate.
See there: 
https://github.com/KiwiHC16/Abeille/issues

**Comment by pipiche38** [comment]
should be close, this is an application issue. Thanks
