### ISSUE TITLE
I would like to approach you with a request to add bin file for jn5169 (last version)

### ISSUE THREAD

**Issue by DmitryBorisenko33** [fairecasoimeme/ZiGate#297]
Please add the latest version bin file for jn5169. The [file](https://github.com/fairecasoimeme/ZiGate/tree/master/Module%20Radio/Firmware/bin/ZiGate/JN5169) that uploaded now 2 years old.

Thank you very much for your work.

**Comment by pipiche38** [comment]
what does it bring ?

**Comment by DmitryBorisenko33** [comment]
It bring some chance to castomers use last version of your firmware. It is very important for us. Please...

**Comment by badzz** [comment]
I compiled one for you .. tell me if it works for you
https://github.com/badzz/ZiGate/releases/tag/v3.1c

**Comment by DmitryBorisenko33** [comment]
Thank you very match for this. It is work for me! Thank you!

**Comment by pipiche38** [comment]
can be close ?

**Comment by IoTManagerProject** [comment]
Yes thank you so much!
