### ISSUE TITLE
How to drive Ikea Bul Using ZGUI

### ISSUE THREAD

**Issue by deennoo** [fairecasoimeme/ZiGate#3]
I first want to try to drive my Ikea Bulb Using ZigBee Gateway User Interface

Can you explain us how to please

**Comment by KiwiHC16** [comment]
Have you checked this page http://faire-ca-soi-meme.fr/zigate/2017/11/27/maitrisez-vos-ampoules-zigbee/
and this one:http://faire-ca-soi-meme.fr/test/2017/06/06/ikea-tradfri-zigbee-3-0-compatibilite-zigate/

Basically you activate the ZiGate, set Ch, Activate Network, Set "Permit Join" and reset your bulb.
