### ISSUE TITLE
Missing 0x8049 when requesting Permit to Join Request 0x0049

### ISSUE THREAD

**Issue by pipiche38** [fairecasoimeme/ZiGate#302]
When sending 0x0049 to Zigate to enable the Permit To Join, Zigate return 0x8000 , but never returns 0x8049 which is expected as per documentation.

Last when sending 0x0049 to a dedicated router, it does return 0x8049

**Comment by fairecasoimeme** [comment]
I think, ZiGate never receive the PERMIT_JOIN_RESPONSE when it requests it for itself.

Doc must be updated

**Comment by pipiche38** [comment]
This will be inconcistent with sending a Permit to Join to a Router
