### ISSUE TITLE
Allow the possibility to send ZCL command without Ack/Nack

### ISSUE THREAD

**Issue by pipiche38** [fairecasoimeme/ZiGate#304]
Quiet a number of ZCL commands expects a Response, like 0x0100 .... In such it doesn't make sense have in addition an Ack/Nack messages.

It would be a great to have an additional parameter which can be at the end of Command Payload to disable the Ack/Nack.

**Comment by fairecasoimeme** [comment]
Hi,

I think you can send ZCL command without ack with changing mode. By default, mode 0x02 is used but you can use mode 0x07 (without ack).
Fred

**Comment by pipiche38** [comment]
You right!
