### ISSUE TITLE
Get list of device provisionned on ZiGate

### ISSUE THREAD

**Issue by pipiche38** [fairecasoimeme/ZiGate#321]
As a device can be provisioned directly on the Gateway (ZiGate) or on any routers, it would be good to know the list of devices which are registered in the Gateway.

This is somehow different than the routing information that we can get via the neighbour query.

**Comment by tcharp38** [comment]
Getting the list zigate known devices is key to ensure system and zigate are "in line" and therefore improve stability.
If possible, it's really worth to implement.

**Comment by tcharp38** [comment]
You closed this because ? No way to implement this ? No sense ?
