### ISSUE TITLE
OSX: mise à jour impossible

### ISSUE THREAD

**Issue by Menucraft** [fairecasoimeme/ZiGate#327]
Bonjour,
près plusieurs heures de test, impossible de mettre à jour ma zigate en 3.1d, j'ai aussi tenté la 3.1c...
Ci dessous le texte dans le terminal
Merci de votre aide!!
MacBook-Pro:~ XXXXX$ ls /dev/cu.* 
/dev/cu.Bluetooth-Incoming-Port	/dev/cu.usbserial
MacBook-Pro:~ XXXXX$ cd JennicModuleProgrammer
MacBook-Pro:JennicModuleProgrammer XXXXX$ cd Build
MacBook-Pro:Build XXXXX$ make
make: Nothing to be done for `all'.
MacBook-Pro:Build XXXXX$ ./JennicModuleProgrammer -V 6 -P 115200 -f « </Users/XXXXX/Desktop/ZiGate_v3.1d.bin> » -s /dev/cu.usbserial
Could not open firmware file

**Comment by pipiche38** [comment]
Ce ne serait pas plus simple de voir avec le forum en charge Zigate ?

http://zigate.fr/forum
