### ISSUE TITLE
 Pb fonctionnement capteur ouverture/fermeture et bouton aqara

### ISSUE THREAD

**Issue by seb19270** [fairecasoimeme/ZiGate#33]
Bonjour,

Je débute avec ma Zigate. Je n'arrive pas à faire fonctionner en même temps un capteur ouverture/fermeture et un bouton aqara. Dans le fichier plugin.py si ligne 11OO est égal à : if MsgAttrID=="0000": alors le capteur fonctionne mais le bouton reste toujours à 1 click et si la ligne 1100 est égal à : if MsgAttrID=="8000": alors le bouton fonctionne mais pas le capteur.

Voila j'espère avoir été clair.

Merci

Sébastien

**Comment by zaraki673** [comment]
problème a voir ici : https://github.com/sasu-drooz/Domoticz-Zigate/issues/71

;)  je regarde la semaine prochaine

**Comment by seb19270** [comment]
Merci, en tout cas super travail.
