### ISSUE TITLE
Doc: Missing address in 8701 cmd and what about swap ?

### ISSUE THREAD

**Issue by tcharp38** [fairecasoimeme/ZiGate#331]
I've understood (and I see the address in 8701 packet), that there is a short address in this message.

Please update the doc page: https://zigate.fr/documentation/commandes-zigate/

Also, what about swap or not between "status" & "nwk status" ? If answer is clear, please update corresponding doc.

Sorry to bother you @fairecasoimeme 
The doc is key for discussions & improvements. This is the ref.

Thanks

**Comment by fairecasoimeme** [comment]
you're right status and nwk status is swapped and there is a target short address.
Doc updated
