### ISSUE TITLE
Doc: Command 0302 undocumented

### ISSUE THREAD

**Issue by tcharp38** [fairecasoimeme/ZiGate#336]
@fairecasoimeme 
Please update doc and add 0302 cmd detail.
Thanks

**Comment by pipiche38** [comment]
This message has been introduced with firmware 31d.

This message is sent by the ZiGate when the PDM has been loaded (either from EEPROM or from Host) and tell that the ZiGate is ready.

**Comment by KiwiHC16** [comment]
https://zigate.fr/documentation/deplacer-le-pdm-de-la-zigate/
E_SL_MSG_PDM_LOADED = 0x0302

**Comment by KiwiHC16** [comment]
![Capture d’écran 2020-11-20 à 00 37 18](https://user-images.githubusercontent.com/8549674/99737423-8cdc3680-2ac8-11eb-86a3-2dcb54350984.png)

**Comment by fairecasoimeme** [comment]
Doc updated
