### ISSUE TITLE
Zigate quitte l'inclusion suite action exterieure

### ISSUE THREAD

**Issue by tcharp38** [fairecasoimeme/ZiGate#337]
J'avoue etre de + en + perplexe vis à vis du comportement de la zigate dans certains cas (certains sont loggué ici), surtout en 3.1d.
Il se passe des choses que je ne comprends pas.
J'avais déja vu ça l'autre jour
- je mets la zigate en inclusion
- je tente de réinclure mes volets profalux
- et je constate que la telecommande profalux (l'action sur) a stoppé le mode inclusion. Elle ne clignote plus. Pourtant c'est sur que la demande d'arret n'a pas été envoyé à la zigate.

Ca vous parle ?
Comment est ce possible ?
Merci

**Comment by pipiche38** [comment]
Quelle action as-tu fait sur la télécommande du profalux, car effectivement l'appui sur STOP va fermer le réseau

**Comment by tcharp38** [comment]
Ha, ca c'est possible car ca fait partie de la recommandation Profalux.
Ok donc on peut fermer le reseau de l'exterieur sans envoyer d'ordre à la zigate. 
Mais cette derniere ne remonte aucun evenement dans ce sens si on ne l'interroge pas.
On est en ligne ?

**Comment by pipiche38** [comment]
Je ne pense pas que ce soit la recommandation Profalux. En fait le STOP permet simplement de vérifier que le Volet a bien été appairé car il va faire un va-et-vient lors de la fermeture du reseau.

Pour moi en faisant le STOP, la remote va envoyer un broadcast à tous les routers (dont la Zigate) avec un permit to join à 0, ce qui ferme le réseau.

**Comment by tcharp38** [comment]
Le stop est meme recommandé par @fairecasoimeme 
![image](https://user-images.githubusercontent.com/35221038/99587450-6bf0e400-29e9-11eb-95af-60ef72ba03d6.png)

mais ca n'est pas ecrit qu'on verifie quoi que ce soit alors.
Bref je sais pas si il a un interet ou pas.

**Comment by pipiche38** [comment]
je pense que tu confond recommandé et faisant partie de a procédure Profalux. Et dans ce cas, effectivement le STOP consiste à fermer le reseau pour vérfier par le va-et-vient du volet que celui-ci a bien été inclus.

**Comment by pipiche38** [comment]
not a problem . should be close

**Comment by tcharp38** [comment]
I agree.
