### ISSUE TITLE
Change channel on PiZiGate

### ISSUE THREAD

**Issue by Kalypox** [fairecasoimeme/ZiGate#338]
Hello,

I'm trying to add a Livolo switch to my PiZiGate (with ZigPy/HA) but it doesn't work.
After research, i saw i had to change the channel but I don't find the procedure to set the channel 26 on my PiZiGate.
The only information is here :
https://zigate.fr/documentation/changer-le-canal-zigbee-pour-les-appareils-livolo/
And it's for ZiGate on Windows. I have PiZigate on Debian.

Thanks

**Comment by doudz** [comment]
You have to check the doc of zha

**Comment by doudz** [comment]
https://www.home-assistant.io/integrations/zha/#defining-zigbee-channel-to-use

**Comment by Kalypox** [comment]
I tried this:
![image](https://user-images.githubusercontent.com/2879180/99908152-3bf35a80-2ce1-11eb-810a-3841dc0d0a47.png)

But nothing happens

**Comment by Kalypox** [comment]
I also tried this:

zha:
  zigpy_config:
    device:
      path: /dev/serial0
      baudrate: 115200
    network:
      channel: 26
      channels: [15, 26]

**Comment by Kalypox** [comment]
I tried a lot of possibilities. This is my swich:
https://www.aliexpress.com/item/32919238619.html
Maybe it's not possible to bind it with PiZiGate

**Comment by pipiche38** [comment]
Please can you use the proper forum. This GitHub is to manage Firmware issues !

**Comment by Kalypox** [comment]
np, where is the proper forum ?

**Comment by doudz** [comment]
Open an issue on home assistant core github

**Comment by Kalypox** [comment]
ok thanks
