### ISSUE TITLE
Doc: message 0x9999 undocummented

### ISSUE THREAD

**Issue by G1K** [fairecasoimeme/ZiGate#347]
@fairecasoimeme

Do I understand correctly that the error code is this data?

https://github.com/fairecasoimeme/ZiGate/blob/aac14153db332eb5b898cba0f57f5999e5cf11eb/Module%20Radio/Firmware/src/sdk/JN-SW-4170/Components/ZPSNWK/Include/zps_nwk_pub.h#L89-L115

Please update the documentation

**Comment by pipiche38** [comment]
yes it is
