### ISSUE TITLE
Réponse 0x8401 IAS Zone Status Change non documenté

### ISSUE THREAD

**Issue by doudz** [fairecasoimeme/ZiGate#35]
La réponse 0x8401 IAS Zone Status Change n'est pas listé dans la documentation http://zigate.fr/wiki/commandes-zigate/

Cette réponse est utilisé par plusieurs capteurs notamment les capteurs de présence, inondation, incendie...

http://zigate.fr/pluzzy-2-1-capteur-de-presence/

**Comment by deennoo** [comment]
Idem sur le capteur d'ouverture Salus et le Nexbang.

**Comment by fairecasoimeme** [comment]
Updated on  http://zigate.fr/wiki/commandes-zigate/
