### ISSUE TITLE
Doc: 8120 response needs update

### ISSUE THREAD

**Issue by tcharp38** [fairecasoimeme/ZiGate#354]
Please update doc to precise that 2 messages formats can be received.

- if the lenght of the payload is 7 bytes, this is E_ZCL_CBET_REPORT_ATTRIBUTES_CONFIGURE_RESPONSE
- if the lenght is greater than 7 bytes then it is E_ZCL_CBET_REPORT_ATTRIBUTES_CONFIGURE_RESPONSE

**Comment by fairecasoimeme** [comment]
updated
