### ISSUE TITLE
Not an ZiGate Issue, but for info - Profalux do not provide Relation ship in LQI Management Response

### ISSUE THREAD

**Issue by pipiche38** [fairecasoimeme/ZiGate#355]
When using the Link Quality request to retreive the Neighbor Table , it looks like Profalux doesn't populate the Relationship information !

I have reported to profalux this matter

**Comment by tcharp38** [comment]
@pipiche38 Talking about profalux, do you know if there are FW updates ?
Initial identifaction was done with "location" instead "modelIdentifier". I'm wondering if they changed this.

**Comment by pipiche38** [comment]
Last time I spoke with them , this was not in their Roadmap

They do consider that the Model in in attribute 0x0010 where there put Volet or BSO

**Comment by tcharp38** [comment]
Thanks
Strange they choose to be so "no standard", like the pb you just reported.

**Comment by pipiche38** [comment]
Discussed with Profalux, and in fact the relationship set as None is correct. It means they are neighbour without a Parent/child or Sibling relationship.
In other terms they are at the same horizontal level but do not share the same parent.
