### ISSUE TITLE
Possibilité de récupérer une valeur sur PIR aqara

### ISSUE THREAD

**Issue by rollyfx** [fairecasoimeme/ZiGate#36]
Bonjour,

Ayant des animaux à la maison, je me demandais si il serait possible de récupérer une valeur décimale représentant "la taille" de la détection plutôt que d'avoir un booléen de retourné.

Ceci afin de pouvoir exclure les animaux plus petits que les humains afin d'éviter les faux positifs.

**Comment by KiwiHC16** [comment]
Non, ils ne remontent qu'un binaire....

**Comment by fairecasoimeme** [comment]
Désolé, en effet, le capteur ne remonte qu'un booléen
