### ISSUE TITLE
Doc update: missing 0122 read configure reporting & 8122 reponse

### ISSUE THREAD

**Issue by tcharp38** [fairecasoimeme/ZiGate#373]
Cmd 0122 is supported (at least on 3.1e) but is not documented.
Same case for 8122 response.

**Comment by tcharp38** [comment]
8122 response format:

>             // <Sequence number: uint8_t>
>             // <Src address : uint16_t>
>             // <Endpoint: uint8_t>
>             // <Cluster id: uint16_t>
>             // <Status: uint8_t>
>             // Attribute type : uint8_t
>             // Attribute id : uint16_t
>             // Max interval : uint16_t
>             // Min interval : uint16_t
> 

WARNING: Compared to NXP spec, min & max seem inverted

**Comment by fairecasoimeme** [comment]
Updated
