### ISSUE TITLE
Integrate and support new Aqara Door Sensor MCCGQ14LM

### ISSUE THREAD

**Issue by pipiche38** [fairecasoimeme/ZiGate#381]
It looks like the new Aqara Door Sensor ( MCCGQ14LM ) does a Node Descriptor toward ZiGate and in that case the ZiGate (Controleur) MUST answer with Xiaomi manufacturer code.

Please do implement such feature as it has been done by the other GW ( z2m, deConz ) so Zigate can support that model 

CC: https://github.com/dresden-elektronik/deconz-rest-plugin/issues/5403#issuecomment-980436576

**Comment by tcharp38** [comment]
We should receive a 8002 message isn't it ?
Then the plugin could answer.
Am I correct ?

**Comment by pipiche38** [comment]
There no reason to get a 8002 as the firmware is processing and responding to this message. Which is the issue I reported. Zigate is answering the Node Descriptor request with a node descriptor response ( which details Zigate info like zigate manuf code) and here we want in that case à Xiaomi manuf code 
Envoyé de mon iPhone

**Comment by tcharp38** [comment]
Ok I missed that.
Zigate is handling response but you need to set a custom response.
Thanks

**Comment by pipiche38** [comment]
Here is what have been done for z2m and there is a similar one for deConz
https://github.com/Koenkk/Z-Stack-firmware/blob/f29b4525bb7bfdc28c91139d0926469bb5754ab9/coordinator/Z-Stack_3.x.0/firmware.patch#L533

**Comment by rcrocus** [comment]
Hello,
Is that possible to make this evolution on the V1 firmware (not only for the V2) ?
Thanks a lot.

**Comment by rcrocus** [comment]
Hello,
After the upgrade of my Zigate v1 to v3.21, it works perfect.
Thanks a lot to everyone.
