### ISSUE TITLE
Response 0x8140 : not enough information

### ISSUE THREAD

**Issue by doudz** [fairecasoimeme/ZiGate#39]
The response 0x8140 should include short addr or ieee , endpoint id and cluster id because without that we don't know what we are talking about
```

Obj-> ZiGate | 0x8140 | Attribute Discovery response | 
  |   |   | <complete: uint8_t> |  
  |   |   | <attribute type: uint8_t> |  
  |   |   | <attribute id: uint16_t> |  
  |   |   | Complete: |  
  |   |   | 0 – more attributes to follow |  
  |   |   | 1 – this was the last attribute

```

**Comment by KiwiHC16** [comment]
Yep, I did the same request. One solution is to use the SQN (sequence number).

**Comment by doudz** [comment]
Why not, but it would be easier to have the addr

**Comment by KiwiHC16** [comment]
I agree

**Comment by nouknouk** [comment]
+1
the same for me

**Comment by pipiche38** [comment]
+1

**Comment by doudz** [comment]
But it seems that many devices don't support Attribute Discovery, so is it really important ?

**Comment by nouknouk** [comment]
for mebit is all the difference between:
- zigate software which can only work with "hard coded" list of known devices.
- zigate software which can also propose all standard features available on an newly included device, even if this device is not yet supported by the software.

So, yes, for me this is somethings that provides added value.

**Comment by doudz** [comment]
Any update to this issue ? this can really make things smoother

**Comment by doudz** [comment]
https://github.com/fairecasoimeme/ZiGate/pull/85

**Comment by pipiche38** [comment]
I think that is cover as part of 3.0f

**Comment by ISO-B** [comment]
Documentation seems to be update also. Someone open this again if this is still problem, but seems to be fixed.
