### ISSUE TITLE
More clarifications on the protocol

### ISSUE THREAD

**Issue by loicortola** [fairecasoimeme/ZiGate#4]
Hi everyone,

since it took me quite some time to figure out how the protocol was engineered by lack of clarity in the resources, let me share it with you.

# Protocol

`"^" is the XOR operator`

## Outbound Message

An **Outbound Message** (PC-2-Zigate) is formed like this :
 * **COMMAND** : 2 bytes, value N is anything btw `0x0000` and `0xffff`, little-endian
 * **LENGTH** : 2 bytes, value is anything btw `0x0000` and `0xffff`, little-endian
 * **CHECKSUM** : 1 byte, value is the lower byte of `0x00 ^ COMMAND ^ LENGTH ^ DATA`.
 * **DATA** : N bytes (N is btw 0 and 0xffff)

## Inbound Message

An **Inbound Message** (Device-2-Zigate-2-PC) is formed like this :
 * **COMMAND** : 2 bytes, value N is anything btw `0x0000` and `0xffff`, little-endian
 * **LENGTH** : 2 bytes, value is anything btw `0x0000` and `0xffff`, little-endian
 * **CHECKSUM** : 1 byte, value is the xor of **EACH** byte of `0x00 ^ COMMAND ^ LENGTH ^ DATA ^ RSSI`.
 * **DATA** : N-1 bytes (N is btw 0 and 0xffff)
 * **RSSI** : 1 byte, from 0x00 to 0xff. Value is 0x00 when message coming from Zigate, 0x01 to 0xff when coming from Zigbee Device.

## Frame encoding

When sending a message (outbound OR inbound), it needs to be encoded this way : 
 * **START** : 1 byte, value is always `0x01`
 * **ENCODED** FRAME : see encoding below
 * **STOP** : 1 byte, value is always `0x03`

The encoding is the following:
Let **B** any byte value of the message.
If B is between `0x00` and `0x09` (included) then :
 * Instead of B, a 2-byte content will be written in the encoded frame
 * The first byte is a fixed value: `0x02`
 * The second byte is the result of B ^ 0x10

# Examples

## Example 1 : Outbound

Outbound Message : 
 * Code : 0x0010
 * Length : 0x0000
 * Checksum : 0x00 ^ 0x0010 ^ 0x0000 = 0x10

Resulting Frame :
 * Start : 0x01
 * Code : 0x0210 0x10
 * Length : 0x0210 0x0210
 * Checksum : 0x10
 * Stop : 0x03

Bytes written on link : **01 02 10 10 02 10 02 10 10 03**

## Example 2 : Inbound

Incoming Frame :
 * Start : 0x01
 * Code : 0x80 0x0210
 * Length : 0x0210 0x0215
 * Checksum : 0x95
 * Data : 0x0210 0x0210 0x0210 0x10
 * RSSI : 0x0210
 * Stop : 0x03

Bytes read on link : **01 80 02 10 02 10 02 15 95 02 10 02 10 02 10 10 02 10 03**

Decoded Incoming Frame :
 * Start : 0x01
 * Code : 0x80 0x00
 * Length : 0x00 0x05
 * Checksum : 0x95
 * Data : 0x00 0x00 0x00 0x10
 * RSSI : 0x00
 * Stop : 0x03

Inbound Message :
 * Code : 0x8000
 * Length : 0x0005
 * Checksum : 0x95 = 0x00 ^ 0x80 ^ 0x00 ^ 0x00 ^ 0x05 ^ 0x00 ^ 0x00 ^ 0x00 ^ 0x10 ^ 0x00
 * Data : 0x0000001000

Hope this helps. @fairecasoimeme please let me know if this is correct, and also help me with this really weird "RSSI" thing.
Honestly, I think it makes no sense to put it after the data anyway!
RSSI should be in the headers and mandatory (or should never be there at all)

**Comment by fairecasoimeme** [comment]
Hi,
The encoding data way is only for 0x00 to 0x09 bytes. It's used to escape data which is not a command.
For example, the byte 0x05 is encoding : 0x02 0x15
the byte 0x01 is encoding :0x02 0x11

Concerning RSSI, if the packet come from a device the byte before the end of packet is the RSSI. The value of RSSI (in this case) could be between 0x01 and 0xff

When packet come from ZiGate the RSSI value is 0x00.

You have to check the [example in PHP](http://zigate.fr/wiki/exemple-api-en-php/), there are more informations.

I hope you find what you search.

Best regards.
Fairesoimeme

**Comment by loicortola** [comment]
Hello,
Thanks for the response! I will update the message accordingly.

One last question : 
In my second example, I see no RSSI byte though... Or is RSSI part of the "data length"?
Is the checksum also transcoded?

**Comment by fairecasoimeme** [comment]
Sorry I re read my spec and the encoding byte is from 0x00 to 0x0f, you're right.

RSSI byte is in data. So RSSI is part of the "data lenght". In your example RSSI value is 0x00. (just before 0x03)
The checksum is also transcoded

**Comment by KiwiHC16** [comment]
Concerning RSSI, if the packet come from a device the byte before the end of packet is the RSSI. The value of RSSI (in this case) could be between 0x01 and 0xff

Is a field that you added in your firmware version as I don't see it in the NXP initial version ?
What is this RSSI ? Is it measured at equipment level ? Quid if the message is routed between the zigate and the equipment ?
Any docs on how this is measured and where ?

**Comment by fairecasoimeme** [comment]
Yep I added this feature because it's usefull. This is not in the NXP initial version. The RSSI determine the reception power between ZiGate and device. When device is routed, you've got the RSSI of the last router. You can get the value of the RSSI between device and router with a command  LQI req (0x004E)

No docs. I noticed only that the quality is between 1 and 255

**Comment by KiwiHC16** [comment]
Ok this is in line with my understanding ;-)
I'm lucky that you put it at the end as it has visibly no impact on my plugin.
Now that I have a alpha which ork I will look at the LQI info and si what I can do. I have some side script to draw a graph, but let see....
