### ISSUE TITLE
[Question]  Is windowCovering command only available for 3.0f or also in later versions 

### ISSUE THREAD

**Issue by dmsherazi** [fairecasoimeme/ZiGate#403]
The Dcumentation here says only 3.0f
![image](https://user-images.githubusercontent.com/6149070/191752367-cb29c920-993d-4118-9a24-65beb10805ef.png)

**Comment by pipiche38** [comment]
yes it is available upwards. but you can also re-implement them using the 0x0530 command which allow to by-pass the all NXP stack.
You have also zigpy project which implement a full stack to controll the coordinator in a radio hardware indepence.

**Comment by dmsherazi** [comment]
Tested and Works. Although There is a small bug in the TEST GUI linked here 
 -> https://github.com/fairecasoimeme/ZiGate/issues/125#issuecomment-1255016373
 Bug -> The Extra command param must be a u16 and not u8
