### ISSUE TITLE
[Question]  what is the diffrence between OPDM and Legacy versions?

### ISSUE THREAD

**Issue by dmsherazi** [fairecasoimeme/ZiGate#404]
In 3.2x there are two versions in the releas list: Legacy and OPDM , what is the diffrence between them?

**Comment by tcharp38** [comment]
Hello.
There is an internal table to store known devices .. this is the "PDM".

- "legacy" means this is the old format of this table
- "opdm" means this is the optimized format allowing more devices before table full and more robustness. This is the recommended FW but this will force to clear PDM (or erase EEPROM) then re-pair ALL devices.

Hope this helps

**Comment by dmsherazi** [comment]
Thanks for the information!
