### ISSUE TITLE
mise à jour impossible

### ISSUE THREAD

**Issue by toto6976** [fairecasoimeme/ZiGate#411]
Bonjour,

J'ai une pizigate v1 (je pense) installée sur une dietpi v.9. Je souhaiterais faire la mise à jour sur le dernier firmware Zigate V3.23 (opdm) ou (legacy);
J'ai l'erreur suivante : 
```
dietpi@DietPi-Salon:~/JennicModuleProgrammer/Build$ sudo ./JennicModuleProgrammer -V 6 -P 115200 -f ZiGate_v3.23-legacy.bin -s /dev/ttyAMA0
JennicModuleProgrammer Version: 0.6 (r56124)
Setting baudrate: 115200
Error setting baudrate 
```

Pouvez-vous m'aider ?

**Comment by tcharp38** [comment]
Salut @toto6976 
J'ai déja vu passer ce genre d'erreur de mon coté et 2 choses me reviennent en tete
- soit un souci au niveau kernel avec l'UART utilisée par la PiZigate. A voir peut etre dans "dmesg"
- soit la PiZigate n'est pas en mode "flash". Il faut jouer avec les PIOs pour ca comme mentionné dans la doc Zigate

La mise à jour n'est pas prise en compte dans l'environnement dans lequel tu utilises la Zigate ? (Domoticz, Abeille..)

**Comment by toto6976** [comment]
La mise à jour n'est pas prise en compte dans zha.
J'ai configuré comme décrit dans la doc. Ce qui est bizarre c'est que lorsque je passe la commande 'gpio write 0 0' la led se met en bleu faible. Et lorsque je lui passe 'gpio write 0 1' comme décrit dans la doc elle repasse en  bleu fort.

**Comment by toto6976** [comment]
J ai trouvé un poste dans lequel quelqu'un a rencontré des erreurs similaires aux miennes et à réussi la maj avec un tuto. Problème, le site a dû fermer car il n y a rien en ligne. Aurais tu par hasard la liste des commandes citées ci-dessous ?
https://zigate.fr/forum/topic/liste-commandes-maj-firmware-pizigate-v1-raspberry-v3/

**Comment by tcharp38** [comment]
Mais la Zigate est reconnue dans ZHA et fonctionnelle ?
Si non, ca confirme un souci de controle de l UART, probablement utilisée par qqch d'autre.

**Comment by toto6976** [comment]
La zigate est reconnue par ZHA.
Fonctionnelle je ne sais pas : j'essaie en vain d'appairer un capteur de
mouvement sonoff. Zha le reconnaît mais je ne le vois nulle part après !?!

**Comment by toto6976** [comment]
Pour ce qui est de la configuration j'ai un peu galéré car les commandes ne
sont plus les mêmes sous debian.
Donc y'a peut être un truc qui n'est pas comme il faut !

**Comment by toto6976** [comment]
Voilà le retour du test:

***@***.***:~/PiZiGate-tools/test$ sudo ./PiZiGate_test /dev/ttyAMA0
RPI Model searching ...
Warning !!! you must modify /boot/config.txt
Verifying /boot/cmdline.txt ...
+ /boot/cmdline.txt seems to be OK
Verifying /boot/config.txt ...
+ /boot/config.txt seems to be OK
Warning !!! if it's not the case, you have to execute the following
commands :
sudo systemctl disable hciuart
sudo usermod -aG gpio pi
then reboot the PI
Searching /dev/ttyAMA0...
sh: 1: lsof: not found
+ Port : /dev/ttyAMA0 is not used
Verif GPIOs ...
+ GPIO 0 (RESET) --> OK
+ GPIO 2 (FLASH) --> OK
Config GPIOs ...
+ GPIO 0 (RESET) --> OK
+ GPIO 2 (FLASH) --> OK
Opening : /dev/ttyAMA0 ...
+ /dev/ttyAMA0 opened --> OK
+ Packet 01 02 10 10 02 10 02 10 10 03 sent --> OK
- No packet received - size sent : 11 - error : 11

**Comment by tcharp38** [comment]
Les GPIOs semblent controlables et ok mais la Zigate ne repond pas du tout.
Elle a déja fonctionné auparavent ?
Si oui ca semble confirmer un souci de port ttyAMA0. Il faut que personne ne le lise pendant ce test.

**Comment by toto6976** [comment]
Oui, elle a fonctionné sur une autre installation home assistant (core).
Après reboot, j'ai ça 
./PiZiGate_test /dev/ttyAMA0
RPI Model searching ...
Warning !!! you must modify /boot/config.txt
Verifying /boot/cmdline.txt ...
+ /boot/cmdline.txt seems to be OK
Verifying /boot/config.txt ...
+ /boot/config.txt seems to be OK
Warning !!! if it's not the case, you have to execute the following commands :
sudo systemctl disable hciuart
sudo usermod -aG gpio pi
then reboot the PI
Searching /dev/ttyAMA0...
sh: 1: lsof: not found
+ Port : /dev/ttyAMA0 is not used
Verif GPIOs ...
+ GPIO 0 (RESET) --> OK
+ GPIO 2 (FLASH) --> OK
Config GPIOs ...
+ GPIO 0 (RESET) --> OK
+ GPIO 2 (FLASH) --> OK
Opening : /dev/ttyAMA0 ...
+ /dev/ttyAMA0 opened --> OK
+ Packet 01 02 10 10 02 10 02 10 10 03 sent --> OK
+ Packet received --> OK
size : 82
 01 00 80 24 00 0d a4 01 00 00 00 15 8d 00 01 ed f8 8b 0b 00 03
01 80 06 00 02 85 01 00 03
01 80 00 00 05 95 00 00 00 10 00 03
01 80 10 00 05 8f 00 03 03 1a 00 03

**Comment by tcharp38** [comment]
Ha cette fois le test est sucessful.
Tu configure les PIO pour le mode flash et retente le flashage ?

**Comment by toto6976** [comment]
Je veux bien. Tu valides les étapes à chaque fois ?

**Comment by toto6976** [comment]
Gpio mode 0 out
Gpio mode 2 out
Gpio write 2 0
Gpio write 0 0
Gpio write 0 1

**Comment by tcharp38** [comment]
Ca semble correct
Que dit l etape suivante du coup?

**Comment by toto6976** [comment]
Cd JennicModuleProgrammer
Build /
sudo make clean
Sudo make all

**Comment by tcharp38** [comment]
Je ne pige pas ces etapes de compile mais bon tu avais déja le binaire du programmeur.
Tu l'as lancé pour voir ?

**Comment by toto6976** [comment]
sudo ./JennicModuleProgrammer -V 6 -P 115200 -f Zigate_v3.23-legacy.bin -s /dev/ttyAMA0

**Comment by toto6976** [comment]
Setting baudrate 115200
error setting baudrate

**Comment by tcharp38** [comment]
Zut :(
Je vais essayer de retrouver des infos. J'ai deja eu ca mais je ne me souviens pas comment je m'en suis sorti.

En tout cas ma derniere hypothese est plutot vers le programmeur.. peut etre plus compatible avec ta distrib.

**Comment by toto6976** [comment]
La pizigate+ (v2) fonctionnerait ?

**Comment by toto6976** [comment]
OK. Bon je vais me coucher. J'attends de tes nouvelles. 

Merci

**Comment by tcharp38** [comment]
Je te laisserai retenter par curiosité en supprimant l'option "-P"

sudo ./JennicModuleProgrammer -V 6 -f Zigate_v3.23-legacy.bin -s /dev/ttyAMA0

**Comment by toto6976** [comment]
Bonjour,
J'essaie. C'est quoi l'option -P ? Parce que au final je ne sais pas à quoi correspond le "baudrate " !?

Même sortie erreur avec  cette fois un "baudrate 100000"

**Comment by tcharp38** [comment]
Salut
Le baudrate correspond à la vitesse de transfert.

Mais bon on n'a pas avancé du coup.
Ta distrib est quoi ?

**Comment by toto6976** [comment]
Dietpi v9.7 (la dernière). C'est une dérivée de debian 12

**Comment by tcharp38** [comment]
Ok donc le code du programmateur n'est probablement plus compatible.
Comme je risque d'avoir le souci bientot je vais essayer de mon coté de migrer vers qqch de + recent que ma buster/v10.

**Comment by toto6976** [comment]
Dans ZHA, la pizigate est reconnue il me semble :+1: 

PiZiGate
par ZiGate
Micrologiciel : 3.1a 
IEEE: 00:15:8d:00:01:ed:f8:8b
Nwk: 0x0000
Device Type: Coordinator
LQI: Inconnu
RSSI: Inconnu
Dernière vue: 2024-09-09T1
Source d'énergie: Mains0:01:02

**Comment by tcharp38** [comment]
Oui tres bien. C'est en ligne avec le resultat de ton test.

**Comment by toto6976** [comment]
Après; le firmware est en 3.1 çà doit passer avec les appareils zigbee. Mon souci majeur, en dehors de la mise à jour, est que l'appareil que je veux appérer n'apparait pas dans les intégrations ZHA alors que l'appairage semble se faire en partie. Je dis en partie car à la fin je n'ai pas la fenêtre dans laquelle il me demande 'la pièce dans laquelle mettre le capteur de mouvement'. 
Mais c'est peut-être le capteur qui déconne car sonoff semble ne pas l'appairer non plus...
Et comme je débute, je n'ai pas d'autres zigbee sous la main

**Comment by tcharp38** [comment]
3.1a est une antiquité.
Si tu refais qqch de propre tu dois partir en version OPDM 3.23 donc ca fait du sens de faire la mise à jour maintenant.
Je fais des essais de mon coté

**Comment by toto6976** [comment]
Quand j'essaie la version OPDM  3.23, je dois faire l'erase de l'eeprom. Or la valeur -e (pour erase je suppose) dans la commande n'est pas reconnue : 
sudo ./JennicModuleProgrammer -V 6 -e -P 115200 -f "<chemin vers le bin>" -s /dev/ttyAMA0

**Comment by toto6976** [comment]
> 3.1a est une antiquité. Si tu refais qqch de propre tu dois partir en version OPDM 3.23 donc ca fait du sens de faire la mise à jour maintenant. Je fais des essais de mon coté

Home Assistant supervised a détécté la vetusté du firmware car il m'a proposé une mise à jour lors de l'intégration de ZHA. Je n'ai pas voulu la faire car il me semblait avoir lu qqpart que la Pizigate ne devait être mise à jour que via le logiciel du programmateur.

**Comment by toto6976** [comment]
> 3.1a est une antiquité. Si tu refais qqch de propre tu dois partir en version OPDM 3.23 donc ca fait du sens de faire la mise à jour maintenant. Je fais des essais de mon coté

ok. Merci de ton aide.

**Comment by tcharp38** [comment]
> > 3.1a est une antiquité. Si tu refais qqch de propre tu dois partir en version OPDM 3.23 donc ca fait du sens de faire la mise à jour maintenant. Je fais des essais de mon coté
> 
> Home Assistant supervised a détécté la vetusté du firmware car il m'a proposé une mise à jour lors de l'intégration de ZHA. Je n'ai pas voulu la faire car il me semblait avoir lu qqpart que la Pizigate ne devait être mise à jour que via le logiciel du programmateur.

Peut etre que ce programmateur est intégré dans ZHA justement.
A suivre

**Comment by toto6976** [comment]
Oui, mais je ne sais pas comment le rappeler !

**Comment by toto6976** [comment]
En cherchant sur le forum de home assistant je tombe la-dessus : https://www.home-assistant.io/integrations/zha/
et je lis çà dans le paragraphe concernant la 'zigate' : 
Autres adaptateurs ou modules radio zigbee pris en charge mais non recommandés (bon, c'est pas rassurant !)
Radios basées sur les ziGate (par l'intermédiaire de la[zigpy-zigate](https://github.com/zigpy/zigpy-zigate)bibliothèque de zigpy et nécessite un micrologiciel **3.1d** ou plus tard). Mon firmware est le **3.1a**. Donc déjà, çà ne peut pas aller !

Si çà peut t'aider, voici les logs de zha en pièce jointe. Moi, çà ne me parle pas trop :)

"home_assistant": {
    "installation_type": "Home Assistant Supervised",
    "version": "2024.9.1",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.12.4",
    "docker": true,
    "arch": "aarch64",
    "timezone": "Europe/Paris",
    "os_name": "Linux",
    "os_version": "6.1.21-v8+",
    "supervisor": "2024.08.0",
    "host_os": "Debian GNU/Linux 12 (bookworm)",
    "docker_version": "27.2.0",
    "chassis": "",
    "run_as_root": true
  },
  "custom_components": {
    "hacs": {
      "documentation": "https://hacs.xyz/docs/configuration/start",
      "version": "2.0.1",
      "requirements": [
        "aiogithubapi>=22.10.1"
      ]
    },
    "sonoff": {
      "documentation": "https://github.com/AlexxIT/SonoffLAN",
      "version": "3.8.0",
      "requirements": [
        "pycryptodome>=3.6.6"
      ]
    }
  },
  "integration_manifest": {
    "domain": "zha",
    "name": "Zigbee Home Automation",
    "after_dependencies": [
      "onboarding",
      "usb"
    ],
    "codeowners": [
      "dmulcahey",
      "adminiuga",
      "puddly",
      "TheJulianJES"
    ],
    "config_flow": true,
    "dependencies": [
      "file_upload"
    ],
    "documentation": "https://www.home-assistant.io/integrations/zha",
    "iot_class": "local_polling",
    "loggers": [
      "aiosqlite",
      "bellows",
      "crccheck",
      "pure_pcapy3",
      "zhaquirks",
      "zigpy",
      "zigpy_deconz",
      "zigpy_xbee",
      "zigpy_zigate",
      "zigpy_znp",
      "zha",
      "universal_silabs_flasher"
    ],
    "requirements": [
      "universal-silabs-flasher==0.0.22",
      "zha==0.0.32"
    ],
    "usb": [
      {
        "vid": "10C4",
        "pid": "EA60",
        "description": "*2652*",
        "known_devices": [
          "slae.sh cc2652rb stick"
        ]
      },
      {
        "vid": "10C4",
        "pid": "EA60",
        "description": "*slzb-07*",
        "known_devices": [
          "smlight slzb-07"
        ]
      },
      {
        "vid": "1A86",
        "pid": "55D4",
        "description": "*sonoff*plus*",
        "known_devices": [
          "sonoff zigbee dongle plus v2"
        ]
      },
      {
        "vid": "10C4",
        "pid": "EA60",
        "description": "*sonoff*plus*",
        "known_devices": [
          "sonoff zigbee dongle plus"
        ]
      },
      {
        "vid": "10C4",
        "pid": "EA60",
        "description": "*tubeszb*",
        "known_devices": [
          "TubesZB Coordinator"
        ]
      },
      {
        "vid": "1A86",
        "pid": "7523",
        "description": "*tubeszb*",
        "known_devices": [
          "TubesZB Coordinator"
        ]
      },
      {
        "vid": "1A86",
        "pid": "7523",
        "description": "*zigstar*",
        "known_devices": [
          "ZigStar Coordinators"
        ]
      },
      {
        "vid": "1CF1",
        "pid": "0030",
        "description": "*conbee*",
        "known_devices": [
          "Conbee II"
        ]
      },
      {
        "vid": "0403",
        "pid": "6015",
        "description": "*conbee*",
        "known_devices": [
          "Conbee III"
        ]
      },
      {
        "vid": "10C4",
        "pid": "8A2A",
        "description": "*zigbee*",
        "known_devices": [
          "Nortek HUSBZB-1"
        ]
      },
      {
        "vid": "0403",
        "pid": "6015",
        "description": "*zigate*",
        "known_devices": [
          "ZiGate+"
        ]
      },
      {
        "vid": "10C4",
        "pid": "EA60",
        "description": "*zigate*",
        "known_devices": [
          "ZiGate"
        ]
      },
      {
        "vid": "10C4",
        "pid": "8B34",
        "description": "*bv 2010/10*",
        "known_devices": [
          "Bitron Video AV2010/10"
        ]
      }
    ],
    "zeroconf": [
      {
        "type": "_esphomelib._tcp.local.",
        "name": "tube*"
      },
      {
        "type": "_zigate-zigbee-gateway._tcp.local.",
        "name": "*zigate*"
      },
      {
        "type": "_zigstar_gw._tcp.local.",
        "name": "*zigstar*"
      },
      {
        "type": "_uzg-01._tcp.local.",
        "name": "uzg-01*"
      },
      {
        "type": "_slzb-06._tcp.local.",
        "name": "slzb-06*"
      },
      {
        "type": "_xzg._tcp.local.",
        "name": "xzg*"
      },
      {
        "type": "_czc._tcp.local.",
        "name": "czc*"
      }
    ],
    "is_built_in": true
  },
  "setup_times": {
    "null": {
      "setup": 0.00025203100000226186
    },
    "01J733XFMT8RMN54846HHAZHNR": {
      "wait_import_platforms": -0.21381161400000792,
      "wait_base_component": -0.005484582999997656,
      "config_entry_setup": 19.557773429999997
    }
  },
  "data": {
    "config": {},
    "config_entry": {
      "created_at": "2024-09-06T07:31:26.490203+00:00",
      "data": {
        "device": {
          "path": "/dev/ttyAMA0",
          "flow_control": null,
          "baudrate": 115200
        },
        "radio_type": "zigate"
      },
      "disabled_by": null,
      "domain": "zha",
      "entry_id": "01J733XFMT8RMN54846HHAZHNR",
      "minor_version": 1,
      "modified_at": "2024-09-06T07:31:26.490227+00:00",
      "options": {},
      "pref_disable_new_entities": false,
      "pref_disable_polling": false,
      "source": "user",
      "title": "",
      "unique_id": null,
      "version": 4
    },
    "application_state": {
      "node_info": {
        "nwk": 0,
        "ieee": "**REDACTED**",
        "logical_type": 0,
        "model": "PiZiGate",
        "manufacturer": "ZiGate",
        "version": "3.1a"
      },
      "network_info": {
        "extended_pan_id": "**REDACTED**",
        "pan_id": 55502,
        "nwk_update_id": 0,
        "nwk_manager_id": 0,
        "channel": 11,
        "channel_mask": 2048,
        "security_level": 5,
        "network_key": "**REDACTED**",
        "tc_link_key": {
          "key": [
            90,
            105,
            103,
            66,
            101,
            101,
            65,
            108,
            108,
            105,
            97,
            110,
            99,
            101,
            48,
            57
          ],
          "tx_counter": 0,
          "rx_counter": 0,
          "seq": 0,
          "partner_ieee": "**REDACTED**"
        },
        "key_table": [],
        "children": [],
        "nwk_addresses": {},
        "stack_specific": {},
        "metadata": {
          "zigate": {
            "version": "3.1a"
          }
        },
        "source": "zigpy-zigate@0.13.1"
      },
      "counters": {},
      "broadcast_counters": {},
      "device_counters": {},
      "group_counters": {}
    },
    "energy_scan": {
      "11": 0.0,
      "12": 0.0,
      "13": 0.0,
      "14": 0.0,
      "15": 0.0,
      "16": 0.0,
      "17": 0.0,
      "18": 0.0,
      "19": 0.0,
      "20": 0.0,
      "21": 0.0,
      "22": 0.0,
      "23": 0.0,
      "24": 0.0,
      "25": 0.0,
      "26": 0.0
    },
    "versions": {
      "bellows": "0.40.5",
      "zigpy": "0.66.0",
      "zigpy_deconz": "0.23.3",
      "zigpy_xbee": "0.20.2",
      "zigpy_znp": "0.12.4",
      "zigpy_zigate": "0.13.1",
      "zhaquirks": "0.0.121",
      "zha": "0.0.32"
    },
    "devices": [
      {
        "manufacturer": "ZiGate",
        "model": "PiZiGate",
        "logical_type": "Coordinator"
      }

**Comment by tcharp38** [comment]
Salut
Bon j'ai bataillé a m'installer une debian 12.. et au final pas de soucis pour compiler et flasher ma PIv1.

Avant de lancer ton "JennicModuleProgrammer" comment controles tu les GPIOs ?

**Comment by toto6976** [comment]
Bonjour
Avec le commande gpio et le test.
Quand tu dis que tu as bataillé, c'est pour la configuration de la pizigate sur la debian ?

Pour l'installation et la configuration de la pizigate j'ai suivi plusieurs tuto : 
1/ https://jeedomiser.fr/article/pilotez-vos-appareils-zigbee-avec-la-pizigate/
2/https://zigate.fr/documentation/parametrer-la-pizigate/
3/http://www.ghanassia.com/?id=installation-configuration-pizigate
4/ https://blog.wijman.net/enable-rc-local-in-debian-bullseye/

Avant de lancer JennicModuleProgrammer je fais çà : 
$ gpio mode 0 out
$ gpio mode 2 out
$ gpio write 2 0 
$ gpio write 0 0
$ gpio write 0 1

puis je lance le test : 
/PiZiGate_test /dev/ttyAMA0

**Comment by tcharp38** [comment]
J'ai bataillé car je suis sur une Debian12 (Armbian) pour Orange pi Zero.
Il manquait pas mal de choses et evidement il y a du changement aussi.

Bref ta sequence GPIO est correcte.
Le test arrive bien à lire la version du FW.
Donc le souci est au niveau du programmateur.

C'est toi qui l'as compilé ou tu as récupéré un binaire ?

**Comment by toto6976** [comment]
Je ne sais plus : sur github je crois.

**Comment by toto6976** [comment]
Tu as un lien ?

**Comment by tcharp38** [comment]
Non ma question est "as tu recupéré un source et tu l'as compilé"
ou l'as tu récupéré tel quel executable ?

**Comment by toto6976** [comment]
Là il me semble : https://github.com/Jerome-PS/JennicModuleProgrammer

et çà ensuite : https://github.com/Jerome-PS/JennicModuleProgrammer.git
cd JennicModuleProgrammer/ 
cd Build/ 
make

mais obligé de passer par #sudo make clean et ensuite #sudo make clean all

Voici le répertoire Build : 
```
~/JennicModuleProgrammer/Build$ ls
Firmware.o                           JN51xx_BootLoader.o     Makefile          ZiGate_v3.23-OPDM.bin    main.o  version.txt
FlashProgrammerExtension_JN5168.bin  JennicModuleProgrammer  ZiGate_v3.1e.bin  ZiGate_v3.23-legacy.bin  uart.o
```

**Comment by toto6976** [comment]
J'ai au début essayé avec 'apt' mais je ne dois pas avoir le dépôt dans mon sources.list

**Comment by tcharp38** [comment]
Je prepare un petit package avec un script et le code du flasher que j'utilise

**Comment by toto6976** [comment]
> Je prepare un petit package avec un script et le code du flasher que j'utilise

Ah...trop bien !! Merci :))

**Comment by tcharp38** [comment]
Tiens essaie avec ca.
J'ai mis toute la trace dans le README.txt

[prog_jennic-0.7-Abeille.zip](https://github.com/user-attachments/files/16980947/prog_jennic-0.7-Abeille.zip)

**Comment by toto6976** [comment]
OK. Merci

**Comment by toto6976** [comment]
en mode $user voilà ce que donne le test :
```
dietpi@DietPi-Salon:~/PiZiGate-tools/test$ ./PiZiGate_test /dev/ttyAMA0
RPI Model searching ...
sh: 1: cannot create model.tmp: Permission denied
Warning !!! you must modify /boot/config.txt
Verifying /boot/cmdline.txt ...                                                                                                                          
sh: 1: cannot create cmdlineTest.tmp: Permission denied
+ /boot/cmdline.txt seems to be OK
Verifying /boot/config.txt ...                                                                                                                           
sh: 1: cannot create configTest1.tmp: Permission denied
sh: 1: cannot create configTest2.tmp: Permission denied
+ /boot/config.txt seems to be OK
Warning !!! if it's not the case, you have to execute the following commands :                                                                           
sudo systemctl disable hciuart                                                                                                                           
sudo usermod -aG gpio pi                                                                                                                                 
then reboot the PI                                                                                                                                       
Searching /dev/ttyAMA0...                                                                                                                                
sh: 1: lsof: not found
sh: 1: cannot create output.tmp: Permission denied
+ Port : /dev/ttyAMA0 is not used
Verif GPIOs ...                                                                                                                                          
+ GPIO 0 (RESET) --> OK
- GPIO 2 (FLASH) --> NOK                                                                                                                                 
Config GPIOs ...                                                                                                                                         
+ GPIO 0 (RESET) --> OK
+ GPIO 2 (FLASH) --> OK                                                                                                                                  
Opening : /dev/ttyAMA0 ...                                                                                                                               
- Error - Unable to open UART.  Ensure it is not in use by another application
```
et en mode #root : 
```
dietpi@DietPi-Salon:~/PiZiGate-tools/test$ sudo ./PiZiGate_test /dev/ttyAMA0
RPI Model searching ...                                                                                                                                  
Warning !!! you must modify /boot/config.txt                                                                                                             
Verifying /boot/cmdline.txt ...                                                                                                                          
+ /boot/cmdline.txt seems to be OK                                                                                                                       
Verifying /boot/config.txt ...                                                                                                                           
+ /boot/config.txt seems to be OK                                                                                                                        
Warning !!! if it's not the case, you have to execute the following commands :                                                                           
sudo systemctl disable hciuart                                                                                                                           
sudo usermod -aG gpio pi                                                                                                                                 
then reboot the PI                                                                                                                                       
Searching /dev/ttyAMA0...                                                                                                                                
sh: 1: lsof: not found
+ Port : /dev/ttyAMA0 is not used
Verif GPIOs ...                                                                                                                                          
+ GPIO 0 (RESET) --> OK
+ GPIO 2 (FLASH) --> OK                                                                                                                                  
Config GPIOs ...                                                                                                                                         
+ GPIO 0 (RESET) --> OK
+ GPIO 2 (FLASH) --> OK                                                                                                                                  
Opening : /dev/ttyAMA0 ...                                                                                                                               
+ /dev/ttyAMA0 opened --> OK
+ Packet 01 02 10 10 02 10 02 10 10 03 sent --> OK                                                                                                       
- No packet received - size sent : 11 - error : 11
```

**Comment by toto6976** [comment]
reboot et en mode $user
```
dietpi@DietPi-Salon:~/PiZiGate-tools/test$ ./PiZiGate_test /dev/ttyAMA0
RPI Model searching ...
sh: 1: cannot create model.tmp: Permission denied
Warning !!! you must modify /boot/config.txt
Verifying /boot/cmdline.txt ...                                                                             
sh: 1: cannot create cmdlineTest.tmp: Permission denied
+ /boot/cmdline.txt seems to be OK
Verifying /boot/config.txt ...                                                                              
sh: 1: cannot create configTest1.tmp: Permission denied
sh: 1: cannot create configTest2.tmp: Permission denied
+ /boot/config.txt seems to be OK
Warning !!! if it's not the case, you have to execute the following commands :                              
sudo systemctl disable hciuart                                                                              
sudo usermod -aG gpio pi                                                                                    
then reboot the PI                                                                                          
Searching /dev/ttyAMA0...                                                                                   
sh: 1: lsof: not found
sh: 1: cannot create output.tmp: Permission denied
+ Port : /dev/ttyAMA0 is not used
Verif GPIOs ...                                                                                             
+ GPIO 0 (RESET) --> OK
+ GPIO 2 (FLASH) --> OK                                                                                     
Config GPIOs ...                                                                                            
+ GPIO 0 (RESET) --> OK
+ GPIO 2 (FLASH) --> OK                                                                                     
Opening : /dev/ttyAMA0 ...                                                                                  
- Error - Unable to open UART.  Ensure it is not in use by another application
```
et en mode # root
```
dietpi@DietPi-Salon:~/PiZiGate-tools/test$ sudo ./PiZiGate_test /dev/ttyAMA0                                
RPI Model searching ...
Warning !!! you must modify /boot/config.txt
Verifying /boot/cmdline.txt ...                                                                             
+ /boot/cmdline.txt seems to be OK
Verifying /boot/config.txt ...                                                                              
+ /boot/config.txt seems to be OK
Warning !!! if it's not the case, you have to execute the following commands :                              
sudo systemctl disable hciuart                                                                              
sudo usermod -aG gpio pi                                                                                    
then reboot the PI                                                                                          
Searching /dev/ttyAMA0...                                                                                   
sh: 1: lsof: not found
+ Port : /dev/ttyAMA0 is not used
Verif GPIOs ...                                                                                             
+ GPIO 0 (RESET) --> OK
+ GPIO 2 (FLASH) --> OK                                                                                     
Config GPIOs ...                                                                                            
+ GPIO 0 (RESET) --> OK
+ GPIO 2 (FLASH) --> OK                                                                                     
Opening : /dev/ttyAMA0 ...                                                                                  
+ /dev/ttyAMA0 opened --> OK
+ Packet 01 02 10 10 02 10 02 10 10 03 sent --> OK                                                          
+ Packet received --> OK                                                                                    
size : 82                                                                                                   
 01 00 80 24 00 0d a4 01 00 00 00 15 8d 00 01 ed f8 8b 0b 00 03                                             
01 80 06 00 02 85 01 00 03                                                                                  
01 80 00 00 05 95 00 00 00 10 00 03                                                                         
01 80 10 00 05 8f 00 03 03 1a 00 03
```

**Comment by toto6976** [comment]
4 réponses dfférentes au test !!! Je ne sais plus quoi penser !?§?
Je continue quand même ??

**Comment by tcharp38** [comment]
Mais pourquoi tu me montres ça ?

Tu decompresses le package que je t'ai donné
tu fais un cd
make clean all
puis flashZigate.sh ... blablabla

Suivre le README

**Comment by toto6976** [comment]
bon...ok
./flashZigate.sh /dev/ttyS1 PI WiringPi ../fw_zigate/zigatev1-AB01-0000-opdm-dev.bin
On est bien d'accord, je remplace /dev/ttyS1 par mon port gpio : /dev/ttyAMA0 ?

**Comment by toto6976** [comment]
```
dietpi@DietPi-Salon:~/prog_jennic-0.7-Abeille$ ls
Makefile  README.md  README.txt  build  flashZigate.sh  source
dietpi@DietPi-Salon:~/prog_jennic-0.7-Abeille$ sudo ./flashZigate.sh /dev/ttyS1 PI WiringPi ../fw_zigate/zigatev1-AB01-0000-opdm-dev.bin
sudo: ./flashZigate.sh: command not found
```

**Comment by tcharp38** [comment]
les droits ne sont surement pas bon

chmod +x flashZigate.sh

**Comment by tcharp38** [comment]
ATTENTION !!
Ton port n'est pas /dev/ttyS1 il me semble mais /dev/ttyAMA0 non ?

**Comment by tcharp38** [comment]
ATTENTION AUSSI !!
Le chemin du FW que je donne est un exemple.
A toi de mettre le bon

**Comment by toto6976** [comment]
> ATTENTION AUSSI !! Le chemin du FW que je donne est un exemple. A toi de mettre le bon

Oh là là !!!!!!!! Je suis fatigué ce soir ! j'ai même oublié de donner les droits !!!

**Comment by toto6976** [comment]
```
$ sudo ./flashZigate.sh /dev/ttyAMA0 PI WiringPi ZiGate_v3.23-OPDM.bin
Checking Zigate type PI access on port /dev/ttyAMA0
- /dev/ttyAMA0 port found
= ERROR: Could not find 'lsof' command
```
`#apt install lsof`

```
$ sudo ./flashZigate.sh /dev/ttyAMA0 PI WiringPi ZiGate_v3.23-OPDM.bin
Checking Zigate type PI access on port /dev/ttyAMA0
- /dev/ttyAMA0 port found
= ERROR: Port is used by process '3329'.
=        You can add '-k' option to further tests anyway.
= Infos:
=   Process 3329 details:
=   PPid=3327, cmd='python3 -m homeassistant --config /config'

= Additional infos I:
[    0.000000] Kernel command line: coherent_pool=1M 8250.nr_uarts=1 snd_bcm2835.enable_headphones=0 snd_bcm2835.enable_headphones=0 snd_bcm2835.enable_hdmi=0 bcm2708_fb.fbwidth=720 bcm2708_fb.fbheight=480 bcm2708_fb.fbdepth=16 bcm2708_fb.fbswap=1 vc_mem.mem_base=0x3f000000 vc_mem.mem_size=0x3f600000  root=PARTUUID=a580676e-02 rootfstype=ext4 rootwait net.ifnames=0 logo.nologo console=tty1 apparmor=1 security=apparmor systemd.unified_cgroup_hierarchy=0
[    0.000733] printk: console [tty1] enabled
[    2.065543] 3f201000.serial: ttyAMA0 at MMIO 0x3f201000 (irq = 99, base_baud = 0) is a PL011 rev2
[    4.148281] systemd[1]: Created slice system-getty.slice - Slice /system/getty.
[   56.798675] ttyd: epoll_ctl support in io_uring is deprecated and will be removed in a future Linux kernel version.

= Additional infos II:
lrwxrwxrwx 1 root root 7 Sep 12 15:53 /dev/serial0 -> ttyAMA0
```

il y a une erreur : ERROR: Port is used by process '3329'.

Sur ce fil, https://community.jeedom.com/t/resolu-pigate-non-vue/51309/4
le type a les mêmes soucis que moi. Et moi aussi, j'ai fait un apt update/upgrade de mon rpi ! Dans son cas ce serait la version de 'wiringpi' qui serait trop vieille. La mienne est installée par 'dietpi-software'. Mais je ne sais pas de quelle version il s'agit.

**Comment by tcharp38** [comment]
Home assistant est en train d'utiliser la Zigate.
il faut l'arreter ou seulement le plugin qui gere la Zigate.
Elle doit etre libre pour pouvoir faire une mise à jour.

**Comment by toto6976** [comment]
Je ne sais pas.comment faire pour arrêter home assistant

**Comment by tcharp38** [comment]
Alors la.. je ne peux pas t'aider. Je ne connais pas cet environnement.
Mais tant qu'il gere la Zigate, aucune chance de la mettre à jour. Il ne peut y avoir qu'un seul controle.

**Comment by toto6976** [comment]
Je vais jeter un œil et demander sur le forum de home assistant. Au pire je l'enlève ce sera pas pire je pense.
Je te tiens au courant

**Comment by toto6976** [comment]
Bonjour,
Mise à jour ok. Merci pour tout. Je vais voir le reste maintenant.
```
$ sudo ./flashZigate.sh /dev/ttyAMA0 PI WiringPi ZiGate_v3.23-OPDM.bin
Checking Zigate type PI access on port /dev/ttyAMA0
- /dev/ttyAMA0 port found
- Port seems free
Configuring PI Zigate for 'flash' mode (lib=WiringPi)
Flashing Zigate
- Port tty: /dev/ttyAMA0
- Type    : PI
- Lib GPIO: WiringPi
- File    : ZiGate_v3.23-OPDM.bin

JennicModuleProgrammer Version: 0.7-r56124-Abeille
- Detected Chip: JN5168
- MAC Address  : 00:15:8D:00:01:ED:F8:8B
Setting baudrate: 115200
Opened firmware file size 194980
Module uses Bootloader v2 Header
Erasing:   100%
Writing Program to Flash
Writing:   100%
Verifying Program in Flash
Verifying: 100%
= Success
Restoring PI Zigate GPIOs config for prod mode
= Tout s'est bien passé. Vous pouvez fermer ce log.
```

**Comment by tcharp38** [comment]
Ha super !
Penses à fermer le sujet du coup.

**Comment by toto6976** [comment]
Peut-être que depuis le début c'était ça le problème !!!!
Et comme par hasard, mon capteur de mouvement reconnu en 2 secondes !

**Comment by tcharp38** [comment]
Peut etre, mais c'est bien pourquoi j'ai ajouté dans mon script ce test d'occupation.

**Comment by toto6976** [comment]
> Peut etre, mais c'est bien pourquoi j'ai ajouté dans mon script ce test d'occupation.

Trop fort !!
