### ISSUE TITLE
Comment actionner la commande on/off sur l'interface GUI vers la prise OSRAM ?

### ISSUE THREAD

**Issue by Mehdi-Hadjali95** [fairecasoimeme/ZiGate#49]
Bonjour, 

J'aurais voulu savoir comment actionner la commande on/off sur l'interface GUI vers la prise OSRAM ? 

Ma prise OSRAM est bien appairé a ma clé Zigate USB mais impossible de savoir comment actionner une commande depuis l'interface, ce n'est pas très clair pour moi la doc officielle. Merci d'avance

**Comment by dondipietro** [comment]
Voici : 
![capture](https://user-images.githubusercontent.com/2470815/43582023-3e45ce90-965b-11e8-914e-88e0d7f5c500.PNG)
