### ISSUE TITLE
Zigate version

### ISSUE THREAD

**Issue by pipiche38** [fairecasoimeme/ZiGate#52]
I have implemented the command 0x0010 in order to receive the Firmware version.
However I saw quiet a number of people with no version at all!

The last one has a Wifi Zigate and so we are wondering if and how to upgrade the firmware ?

**Comment by doudz** [comment]
maybe related to https://github.com/fairecasoimeme/ZiGate/issues/45

**Comment by pipiche38** [comment]
Tend to agree, yes ;-)
