### ISSUE TITLE
0x0015 - GetListOfDevice doesn't provide a consistent list of Device

### ISSUE THREAD

**Issue by pipiche38** [fairecasoimeme/ZiGate#53]
When using 0x0015 , I'm not always via 0x8015 getting a consistent list of devices.

By using the GUI NXP and requesting List of Device we are not always getting the same result !

**Comment by doudz** [comment]
is it WiFi ?

**Comment by pipiche38** [comment]
Doesn't matter. For Wifi it looks like we do not get any answer except that 0x8000, (reported from a user)

On my end , when I use the GUI NXP Windows application I plug the Zigate directly to the USB port !

**Comment by KiwiHC16** [comment]
La Zigate rapporte une liste d'equipement avec laquelle elle a dialogué récemment (C est un peu comme une table arp dans la stack TCP/IP), ce qui explique le comportement que tu observes ?
