### ISSUE TITLE
Remove Device - 0x0026

### ISSUE THREAD

**Issue by pipiche38** [fairecasoimeme/ZiGate#55]
The behaviour of the 0x0026 (Remove device) looks quiet strange.

Either from the Win NXP program or directly from a plugin if you send the 0x0026 with the IEEE address, you get in return a OK Status.

But if after you do a GetListof Device the device is still there.

More, if you do again the same command 0x0026  you get again a Ok Status !

Looks like the device is not really removed !

**Comment by doudz** [comment]
duplicate https://github.com/fairecasoimeme/ZiGate/issues/29
