### ISSUE TITLE
Probleme d'appairage avec device Legrand Netatmo

### ISSUE THREAD

**Issue by Smanar** [fairecasoimeme/ZiGate#59]
Salut, je suis en train de bricoler avec l'inter/variateur Legrand/netamo.
A la sortie de la boite, il s'est appaire sans probleme avec la zigate mais seul le on/off fonctionnait. Du coup j'ai achete la centrale qui allait avec. Apres les mises a jours du firmwares, le variateur fonctionne avec l'instal legrand.
Puis j'ai essaye de le re pairer avec la zigate et la, plus rien, tests sur ZWGUI.

```
Type: 0x004D (End Device Announce)
  Short Address: 0xB748
  Extended Address: 0x47400007A2666
  MAC Capability: 0x8E
    Alternate PAN Coordinator: False
    Device Type: Router
    Power Source: AC
    Receiver On When Idle: True
    Security Capability: Standard
    Allocate Address: True
Type: 0x004D (End Device Announce)
  Short Address: 0xB748
  Extended Address: 0x47400007A2666
  MAC Capability: 0x8E
    Alternate PAN Coordinator: False
    Device Type: Router
    Power Source: AC
    Receiver On When Idle: True
    Security Capability: Standard
    Allocate Address: True
Type: 0x8701 (Route Discovery Confirm)
  SQN: 0x00
  Status: 0x00
  Network Status: 0x87
Type: 0x8048 (Leave Indication)
  Extended Address: 0x47400007A2666
  Rejoin Status: 0x00
```
Y a ca en boucle, en changeant d'adresse puis sur la fin

```
Message: 
Type: 0x804E (Mgmt LQI Response)
  SQN: 0x0F
  Status: 0xC1
  Nb Table Entries: 16
  Start Index: 2
  Nb Table List Count: 11
  Neighbor 0:
    Extended Pan ID: 0x6600848E87000306
    Extended Address: 0x400001C0044474B
    Nwk Address: 0x0026
    LQI: 254
    Depth: 76
    Flags: 0xFF
    Device Type: Unknown
    Permit Joining: Unknown
    Relationship: Unknown
    RxOnWhenIdle: Unknown
  Neighbor 1:
    Extended Pan ID: 0x170019001A002000
    Extended Address: 0x2100220024002500
    Nwk Address: 0x0000
    LQI: 0
    Depth: 38
    Flags: 0x28
    Device Type: Coordinator
    Permit Joining: Unknown
    Relationship: Sibling
    RxOnWhenIdle: No
  Neighbor 2:
    Extended Pan ID: 0x2A400040014002
    Extended Address: 0x400340044006400A
    Nwk Address: 0x0029
    LQI: 11
    Depth: 64
    Flags: 0x40
    Device Type: Coordinator
    Permit Joining: Off
    Relationship: Parent
    RxOnWhenIdle: Yes
  Neighbor 3:
    Extended Pan ID: 0x00000000
    Extended Address: 0x00000000
    Nwk Address: 0x0C00
    LQI: 0
    Depth: 0
    Flags: 0x00
    Device Type: Coordinator
    Permit Joining: Off
    Relationship: Parent
    RxOnWhenIdle: No
  Neighbor 4:
    Extended Pan ID: 0x00000000
    Extended Address: 0x00000000
    Nwk Address: 0x0000
    LQI: 0
    Depth: 0
    Flags: 0x00
    Device Type: Coordinator
    Permit Joining: Off
    Relationship: Parent
    RxOnWhenIdle: No
  Neighbor 5:
    Extended Pan ID: 0x00000000
    Extended Address: 0x00000000
    Nwk Address: 0x0000
    LQI: 0
    Depth: 0
    Flags: 0x00
    Device Type: Coordinator
    Permit Joining: Off
    Relationship: Parent
    RxOnWhenIdle: No
  Neighbor 6:
    Extended Pan ID: 0x00000000
    Extended Address: 0x00000000
    Nwk Address: 0x0000
    LQI: 0
    Depth: 0
    Flags: 0x00
    Device Type: Coordinator
    Permit Joining: Off
    Relationship: Parent
    RxOnWhenIdle: No
  Neighbor 7:
    Extended Pan ID: 0x00000000
    Extended Address: 0x00000000
    Nwk Address: 0x0000
    LQI: 0
    Depth: 0
    Flags: 0x00
    Device Type: Coordinator
    Permit Joining: Off
    Relationship: Parent
    RxOnWhenIdle: No
  Neighbor 8:
    Extended Pan ID: 0x00000000
    Extended Address: 0x00000000
    Nwk Address: 0x0000
    LQI: 0
    Depth: 0
    Flags: 0x00
    Device Type: Coordinator
    Permit Joining: Off
    Relationship: Parent
    RxOnWhenIdle: No
  Neighbor 9:
    Extended Pan ID: 0x00000000
    Extended Address: 0x00000000
    Nwk Address: 0x0000
    LQI: 0
    Depth: 0
    Flags: 0x00
    Device Type: Coordinator
    Permit Joining: Off
    Relationship: Parent
    RxOnWhenIdle: No
  Neighbor 10:
    Extended Pan ID: 0x00000000
    Extended Address: 0x00000000
    Nwk Address: 0x0000
    LQI: 0
    Depth: 0
    Flags: 0x00
    Device Type: Coordinator
    Permit Joining: Off
    Relationship: Parent
    RxOnWhenIdle: No
```

Du coup je me retrouve avec plein de devices bizarres et non fonctionnels, mais impossible d'avoir l'inter (avec l'adrese IEE finissant par 2666)

Edit:
C'est normal ca
`Device Type: Router`
pour l'inter ? et pourquoi a la fin
`Type: 0x8048 (Leave Indication)`

Edit2:
Pour le mode routeur, je viens de comprendre, c'est un device alimente, donc il doit pouvoir relayer le reseau.

**Comment by KiwiHC16** [comment]
Il y a des changements pour Legrand dans la Version 30E à venir. Ceci explique peut être cela.

**Comment by Smanar** [comment]
Ha ? C'est quoi la version 30E ?
Mais le hardware etant le meme, le meteriel fonctionnant deja avant la MAJ du firmware, les differences ne doivent pas etre enormes ?
Pour le moment, pour ce que je comprend, la communication se fait, mais le device attend quelque chose qu'il n'a pas et du coup "leave", puis se reconnecte avec une nouvelle adresse, et rebelotte.

Je changerais bien le firmware de la zigate pr passer en sniffer mais je sais pas trop a quoi je m'attaque, et si c'est a ma ma portee ou pas.

**Comment by KiwiHC16** [comment]
30E est la prochaine version du firmware de la zigate:
https://github.com/fairecasoimeme/ZiGate/tree/master/Module%20Radio/Firmware

"les differences ne doivent pas etre enormes": il suffit d'un bit pour que cela fonctionne ou non.... comme dit il y a des modifications a venir sur le sujet, Akila pourra confirmer.

"Je changerais bien le firmware de la zigate pr passer en sniffer mais je sais pas trop a quoi je m'attaque, et si c'est a ma ma portee ou pas.": c est une partie loin d'être simple. Il y a au minimum deux solutions: une comme expliquée par Akila dans ses articles, une que j'ai dev avec Jerome-PS: https://github.com/KiwiHC16/Butineuse ou https://github.com/Jerome-PS/JN516xSniffer

**Comment by Smanar** [comment]
Ha ^^.
Nope c'est le firmware de du device legrand qui a ete mit a jour.
En fait a la sortie de la boite, tout a fonctionne, puis je l'ai connecte a la centrale pour activer des fonctions manquantes, et la centrale a mit l'appareil a jour, et depuis plus moyen de me conecter, le prb viens de legrand pas de la zigate.

Mais je vais voir les nouveaute du nouveau firmware de la ziagate.

Sinon j'ai vu tes 2 liens, j'etais dessus justement, mais c'est juste que je me vois pas trouver la solution alors que d'autres sont dessus depuis plus de temps que moi. Je veux bien re deconnecter toute mon install zigbee pour faire les tests, mais si on me dit que c'est impossible je laisse tomber.

**Comment by max5962** [comment]
Hello @Smanar 

Les infos que j'ai plus récup à droite à gauche ( github/forum ect ), c'est que legrand a fait une MAJ et BOOM plus compatible avec la zigate. Akila travaille actuellement dessus ( ça doit pas être simple ) pour la rendre de nouveau compatible. Corrigez moi si je dis une bétise.

D'après ce que ce que j'ai lu, le new firmware, devrait inclure : 
- meilleur gestion des modules xiaomi aquara ( pour éviter les leaves ) 
- compatibilité Legrand
- et peu être d'autres joyeusetés :D

**Comment by KiwiHC16** [comment]
Le symptome que tu décris est celui decris par Akila qui a fait une correction dans la Zigate et ca doit être dans la prochaine version du Firmware Zigate (3.0.E).
Je ne retouve plus sont son doc. Mais je suis sure de l'avoir lu.
Il faut donc patienter pour le prochain firmware.

**Comment by Smanar** [comment]
Ha ^^. Put1 merci, vous m'avez remit le moral au moins pour la journee, donc je touche a rien. J'avais vu qu'il avais parle d'une surprise en septembre, mais aucune idee de quoi il s'agissait (quoique normal si il veut faire une surprise).
J'espere qu'il va y arriver, en tout cas si besoin de testeurs, j'ai centrale + inter/variateurs

**Comment by lolorc** [comment]
la surprise devrait aussi être le passage code de la zigate en opensource :-)

**Comment by Smanar** [comment]
Ben d'un cote c'est bien car d'autres vont pouvoir reprendre le projet, mais ca risque d'etre le bordel si tout le monde se retrouve avec un firmware different pour X ou Y raisons.
Par contre vous etes sur de votre coup avec legrand, car la j'ai du temps libre et j hesite vraiment a attaquer mon inter ?

**Comment by Smanar** [comment]
Bon je m'y suis finalement mit mais je decouvre le fonctionnement des outils. Le sniffer c'est bon je gere, par contre quand j'essaye de reproduire les trames avec ZGUI, la c'est autre chose. En fait vu que je n'ai aucune idee de ce qui bloque j'essaye de reproduire a l'identique. Du coup j'aurais quelques questions pour les habituees du "sniffage". 

1 - Apparement cette appli permet surtout d'agir sur le layer zigbee ? APS ce serait interne au firmware et NWK, a part la config de base, suis pas sur de tout avoir ?

2 - Ensuite l'inter ne communique pas directement a la centrale mais passe par la prise, su coup pour reproduire les trames c'est mort ? Meme si je met la zigate en mode routeur ca ne marchera pas car pas de device coordinateur ?

Je demande cela car je bloque des la premiere commande que l'inter fait apres le "Device announce", c'est un "node descriptor request" (ligne 116) qu'il ne fait pas si je simule le fct avec l'appli. Et a part avec des requetes NWK et APS je ne vois meme pas ou il aurait trouve l'adresse pour faire la sienne (associe a la ligne 101).
Une reaction au "parent annce" ? Mais pour reproduire cette requete ........

![petit lien](http://www.noelshack.com/2018-39-3-1537990301-snif) 
http://image.noelshack.com/minis/2018/39/3/1537990301-snif.png

**Comment by pipiche38** [comment]
@Smanar je pense que cela ne va pas aider, mais si j'ai bien compris comment le protocol fonctionne, il te faut comme tu le constates un Coordinateur, et dans ton cas, la Zigate ne peut pas être dans les deux modes ( Sniffeur et Coordinateur).

Le mode routeur quant à lui n'est simplement que pour faire du réseau Mesh, donc je ne pense pas que ça aide.

**Comment by KiwiHC16** [comment]
J'ai le fichier, tu peux l'enlever du serveur. Après un parcours rapide, je note plusieurs choses:
- il y a beaucoup de Join request alors que le réseau dit être fermé. Est ce qu'un autre équipement cherche à se joindre ?
- Il y a des échange de clefs qu'on ne voit pas d'habitude.
- Une commande non décodée, pourquoi ?
- beaucoup de commandes classiques
-  des clusters propriétaires
J'essayerai de comprendre plus à tête reposée ....

**Comment by Smanar** [comment]
En fait j'ai relance la procedure complete, donc c'est l'integralite des trames apres la mise sous tension.
Il y a la telecommande (BP) 53AE qui lance des requetes bizarres et 2 devices normallement (prise + inter).
Et il n'y a que l'inter qui lance un vrai commissioning depuis le debut (Association MAC)

La commande non decodee, je l'ai vu aussi (elle apparait 2/3 fois notament en reaction au bp), mais je l'ai ignore car elle part de la prise vers la centrale, donc meme si elle fait parti du processus, on peut la faire sauter.

Pour les echanges de clef, je pense vraiment que la faille est la, et pour mon malheur c'est totallement non simulable avec ZGWUI, il faut agir sur le firmware de la zigate, d'ailleurs d'apres le code du firmware (un vieux, pas l'actuel) il y aurait moyen d'activer un debug via l' UART qui donnerait plus d'infos notamment pour L'APS et le NWK.
Commande DBG_vPrintf() activee par UART_DEBUGGING True.

Honnetement je ne pense pas que le prb viennent des requetes ZDP, je partirais plutot pour un probleme lors de l'echnage des cle, mais la pour trouver un deboguage .... A moins que tu ais 2 zigates ou 1 zigate + 1 sniffer ?

Mais par rapport au truc recupere sur le site d'akila.
![zigbee_link_key_update_6dec2016](https://user-images.githubusercontent.com/20152487/46192854-b7714100-c2fc-11e8-8bca-dc787b9d3308.png)
Les seules differences que je vois
- le trust center est le routeur assez souvent.
- Par defaut la zigate ne fait jamais le "node descriptor".
Rien de mechant pour moi, c'est quoi les echnages de cle non habituel que tu vois ?

Now j'ai compris pkoi l'inter ne fait pas de "node descriptor" la zigate ne fait pas la requete ligne 103 "parent annce", mais est ce que ca gene ? xiaomi s'en contrefout par exemple.

**Comment by Smanar** [comment]
OK, je viens de voir un commentaire sur son image.
if "stack Compliance Revision" = 0x15 > start Link key update procedure.
Dans mon log c'est le cas.

Jamais avec la zigate car pas de Device announce Broadcast > pas de None Descriptor Req > pas de Node descriptor Response > pas de "Stack compliance revision" > pas de link key update.

**Comment by Smanar** [comment]
Quelqu'un pourrait me dire ce que je pourrais utiliser pour deboguer un firmware installe sur la zigate "en direct" ?
Meme autre chose que l'option JTAG, je cherche la marque "apascher" pour le moment.

**Comment by deennoo** [comment]
En discutant avec un tech legrand lors de la formation Celiane with Netatmo j'ai appris ceci : 

Une prise/modules/inter 230 communique avec la gateway une sorte de start time : 

Il est impératif que les deux soit mis sous tensions en même temps, cela mets en route une horloge, et c'est cette horloge qui doit correspondre sur les deux modules ; exemple sous tension depuis 123456789 ms pour tout le monde.

**Comment by Smanar** [comment]
Ha, je ne vois rien dans les requetes a ce sujet, mais c'est clair que ca doit servir a un moment ou a un autre. Sympa comme info merci ^^.

**Comment by Smanar** [comment]
J'ai du neuf ^^.
Bon comme le projet zigate est mort j'ai change de projet mais en fait la protection vient du routeur, il suffit d'utilser un second device comme routeur, et pour le moment le on/off refonctionne, il me faut encore approfondir le truc mais je confirme c'est possible.

**Comment by fairecasoimeme** [comment]
Pas du tout, je travaille depuis 8h en ce moment même (non stop) pour sortir la 3.0e pour la semaine prochaine...
Y a juste des gens pour qui ça ne va pas assez vite ...
Il suffit juste

**Comment by doudz** [comment]
@fairecasoimeme :+1: bravo et merci pour ton travail
@Smanar attention à ne pas lancer des rumeurs

**Comment by fairecasoimeme** [comment]
D'ailleurs dans la nouvelle version 3.0e, le problème d'appairage avec Legrand est réglé...
Bref ...

**Comment by Smanar** [comment]
Rumeurs ?
Une seule personne sur le projet, qui donne un signe de vie pile tout les 30 jours !
La derniere page sur legrand est un gros gag ( pas jette un oeuil sur la notice, ni les parametres, ni meme sur la gamme netatmo, 3 liens ou "c'est le moins cher", ou un seul proposait un meilleur prix que les 3 autres, autant d'infos donnes qu'on trouvait deja sur les forums.
Sur twitter, un "nouveau device" venant de leroymerlin, deja en place sur les applications domotique depuis plusieurs mois.
Aucunes reponses aux multiples requetes que lui font les membres de la communautee d'un peu partout.

Dsl, mais c'est pas que je trouve que ca avance pas assez vite, mais que ca n'avancera jamais en continuant comme ca,

**Comment by vosmont** [comment]
@Smanar, vous n'étiez peut-être pas présent lors du lancement du projet sur Kickstarter. Je vous conseille de jeter un œil au site http://faire-ca-soi-meme.fr/. Vous y verrez tout le travail accompli pour arriver à la ZiGate.
Je suppose que en plus de sa vie professionelle, @fairecasoimeme a aussi une vie familiale, ce qui peut expliquer que parfois le projet n'aille pas à la vitesse que vous souhaiteriez.
Il ne faut pas oublier non plus que la ZiGate est une passerelle et que les systèmes compatibles font aussi une grosse partie de l'intégration des nouveaux équipements.

**Comment by fairecasoimeme** [comment]
Désolé, c'est surement parce que je n'ai pas ton niveau que mes articles, tweets et produits te semble être un gag technique.
Désolé de ne t'apporter que peu d'informations et de ne pas te donner entière satisfaction.
J'espère que les autres personnes des différentes communautés t'aideront plus que je ne le fais.
Je préfère partager mon temps libre (hé oui je suis salarié la semaine aussi) pour assouvir ma passion ainsi que ma vie de famille au détriment de la rapidité d'avancement du développement de la ZiGate.
C'est un choix que j'assume.
A bientôt.

**Comment by max5962** [comment]
@fairecasoimeme
Hello,
Je préfère être franc avec toi, parce que tu le mérite et ton travail merite reconnaissance.
Le constat de @smanar, même si c'est maladroit est un peu le ressentie de la communauté (francophone ou surtout anglophone soit 80 %  du monde de developpement opensource).

Dans le monde libre, c'est un peu la course contre la montre et sur le sujet du zigbee, tu as démarré avec une longueur d'avance,
tu as ouvert la voie et d'autres ce sont engouffrés (zigbeemqtt en autre).
La fermeture du code (même si a terme tu souhaite l'ouvrir) frustre les développeurs et ne souhaites plus partir la dessus...
J'ai peur que ton travail meure faute d'engouement du public.

Le seul équipement domotique qui tient encore à la zigate a ma connaissance est jeedom,car très francophone.

L'ouverture du code (même si l'acceptation des pullRequests est drastique) serait SELON MOI un signe d'ouverture. Cela permettrait aux developpeurs de t'aider et passer ton projet a une vitesse supérieur.

J'espère que mon avis sera perçu comme constructif, que tes projets avancent bien.
A bientôt.

N'hésites pas si tu as besoin d'aide  : )
Maxime

**Comment by fairecasoimeme** [comment]
@max5962 merci pour ta franchise mais l'engouement du public ne fais que s'accroître (j'ai battu des records de vente ce mois-ci) et pas que des français (25% d'étranger)
Aujourd'hui, Jeedom, domoticz et eedomus sont actifs... seuls home assistant a été délaissé
Mon objectif a toujours été de rendre libre le firmware pour faire progresser le produit et tous mes retards ont été expliqués sur les réseaux sociaux.

Je ne peux pas communiquer tout le temps car il y a un temps pour tout et ces derniers mois, je le consacre au rattrapage du retard. Je suis toujours à l'écoute des conseils constructifs et même si je n'interviens pas, je suis tous les forums de chaque plugins et box compatibles.

Personne n'a assez d'élément en sa possession pour juger de ma motivation et n'oubliez pas que le projet à plus d'un an et que je suis toujours dessus ...

Chaque projet concurrent, ou pas, mérite d'exister et c'est à chacun d'aller où bon lui semble.

**Comment by fairecasoimeme** [comment]
Ce problème est corrigé dans la version 3.0e.

Lors du premier essai, il se peut que l'appareil Legrand Netatmo se mette en rouge. Il suffit de re-appuyer sur le bouton d'appairage 1 seul fois et le matériel sera définitivement appairé à la ZiGate
