### ISSUE TITLE
Compatibilité Tradfri <-> Zigate

### ISSUE THREAD

**Issue by ChoOo7** [fairecasoimeme/ZiGate#65]
Bonjour

J'ai associé avec succès ma télécommande Tradfri à ma zigate, puis mon ampoule tradfri à ma zigate, puis enfin la télécommande à l'ampoule.

Lorsque je fais cela, les boutons de la télécommande permettant de de passer d'une lumière ,plus ou moins chaude / froide ne marchent plus. (cela correspond au boutons marqués d'une flèche).

Si je fais un factory reset de l'ampoule, de la télécommande et que je les associe ensemble directement, pas de soucis.

Si je recommence le process du dessus pour que la zigate puisse communiquer avec l'ampoule, j'ai de nouveau le souci.

Merci

**Comment by pipiche38** [comment]
Peut-etre que je vais dire des bétises, mais Il me semble que Akila explique dans sa communication que la télécomande pilote un groupe/scène. 

Alors lorsque tu associes la télécommande à la Zigate, je pense qu'il te reste l’étape: "associer la télécommande à un groupe" Pourquoi la télécommande arrive à faire OnOff et faire le LevelControl et pas le color control ... aucune idée ...

**Comment by Smanar** [comment]
C'est normal, j'ai deja fais des tests.
La couleur ne se fait pas avec le "color" control, mais avec le "scene" control (quand elle est appairee avec la telecommande), c'est pour ca que quand on fait avec la telecommande, la variation se fait par couleur memorisee ,il n'y a pas une infinitee de couleurs mais une vingtaine (ou meme moins, me souvient plus), en fait quand on appuis sur le boutton ca passe a la scene suivante ou precedente.
Quand on passe par la zigate, le fonctionnement par "scene" ne se met pas en place sur les appareils.

**Comment by ChoOo7** [comment]
Humm intéressant.
En effet, il y a un nombre limité de "couleur", 3 ddans mon cas (blanc, chaud, et vraiment vraiment jaune)
Ce que j'ai du mal à saisir, c'est que une fois que la télécommande et l'ampoule sont associés au zigate, on fait un appareillage "normal" entre la télécommande et l'ampoule.

Et ce qui m'échappe c'est pourquoi à ce moment là, le mécanisme n'est pas autonome, pourquoi le fait que la zigate soit dans la boucle les gênent pour faire leur bazar.

**Comment by Smanar** [comment]
Peu etre que les echanges pr la mise en place des scene ne se font que durant (ou plutot juste apres) le commissioning. Donc toi tu fais
Telecommande > zigate (commissioning)
Ampoule zigate > zigate (commisioning)
Telecommande> zigate (touchlink)

Tout ce beau monde se retrouve sur le meme groupe, mais a aucun moment l'ampoule a eu l'occasion de "discuter en direct" avec la telecommande.

Apres avec le logiciel ZGWUI/TESTGUI il y a surement la possibilite de creer tes propres "scenes".

**Comment by KiwiHC16** [comment]
Les boutons < et > de la telecommande utilisent les scenes. Il faut definir les scenes...

**Comment by pipiche38** [comment]
This should be close. It has been adressed in 1.30f
