### ISSUE TITLE
0x0140 - Attribute Discovery request

### ISSUE THREAD

**Issue by pipiche38** [fairecasoimeme/ZiGate#67]
Did you try this command ?

I've tried it against few equipement, but didn't get any answer from the Device.

(1) Send 0x0140
(2) Got 8000 with status Ok on Type 0x0140

But I never get it 0x8140

I tried to put on Permit to Join and start the Pairing process, while requesting 0x0140 on few Clusters which are provided by the Device via 0x8045/0x8043 but nothing arrive

**Comment by doudz** [comment]
Attribute discovery is not supported on all device
https://www.nxp.com/docs/en/user-guide/JN-UG-3077.pdf, page 44
