### ISSUE TITLE
Enumerating associated devices

### ISSUE THREAD

**Issue by blubber** [fairecasoimeme/ZiGate#7]
Is it possible to get a list of devices that are associated with the Zigate?

**Comment by blubber** [comment]
After trying a lot of different things @tjikkun figured out how to do this. Broadcasting a match descroptor request (`0x46`) to `0xfffd` with profile `0xffff` and no clusters will provoke a response from all devices, at least from all Ikea Tradfri bulbs :).

**Comment by fairecasoimeme** [comment]
In the last version of firmware (3.0b) I add this function (0x0015) 
http://zigate.fr/wiki/commandes-zigate/

**Comment by blubber** [comment]
Great, thanks! 👍
