### ISSUE TITLE
Add doc for 0x0016 and 0x0017 commands and response 0x8017

### ISSUE THREAD

**Issue by doudz** [fairecasoimeme/ZiGate#73]
Could you add doc for new commands 0x0016 and 0x0017 and response 0x8017 ?

**Comment by pipiche38** [comment]
@doudz any hints on what are they ?

**Comment by doudz** [comment]
just read the change log
0x0016 :  set time
0x0017 : get time
0x8017 : get time response

**Comment by doudz** [comment]
Yes, that's what I coded https://github.com/doudz/zigate/blob/master/zigate/core.py#L653
But official doc will be appreciate ;)

**Comment by fairecasoimeme** [comment]
Sorry but I modified the set time protocol. It's ok in the 3.0f branch. if you want, just update the app_znc_cmds.c.
The detail of protocol is in command page on the website : https://zigate.fr/wiki/commandes-zigate/

**Comment by doudz** [comment]
Thanks !
