### ISSUE TITLE
Is there a way to disable the Zigate Led

### ISSUE THREAD

**Issue by pipiche38** [fairecasoimeme/ZiGate#77]
Do we have the possibility to switch off the Led ?

**Comment by fairecasoimeme** [comment]
not with a serial command... only with update source ...
Why do you want to switch off LED ?

**Comment by pipiche38** [comment]
I don't need chrismas trees ;-)

More seriously they are a number of end devices where you can tuned down the luminescence of the led and eventually turn it off, and I don't really need the LED. 
The initial Zigate I have doesn't have any led and I'm pretty happy with.

**Comment by fairecasoimeme** [comment]
Ok,
I will add a command to switch off LED ... in the next firmware. 3.0f

**Comment by pipiche38** [comment]
Just a nice to have ;-)

**Comment by pipiche38** [comment]
Thanks for implementing it in 3.0f
