### ISSUE TITLE
Get Version result not equal to Firmware version

### ISSUE THREAD

**Issue by doudz** [fairecasoimeme/ZiGate#8]
I recently upgrade to Firmware 3.0a
But when I send the commande 0010 to get version, zigate return 
Major : 1
Installer : 778
This looks like 1.778 not 3.0a or am I wrong ?

Encoded command sent : 01021010021002101003
Encoded answer : 018010021002159d021002110213021a021003

**Comment by fairecasoimeme** [comment]
You have to convert 778 (decimal) to hexadecimal and you will obtain 0x30A.

**Comment by doudz** [comment]
Thanks for explanation
