### ISSUE TITLE
Firmware 3.0f

### ISSUE THREAD

**Issue by ruimarinho** [fairecasoimeme/ZiGate#82]
Hi,

Could you publish the binary for 3.0f please? 

Thank you,

**Comment by Smanar** [comment]
It's note same ?
https://github.com/fairecasoimeme/ZiGate/tree/master/Module%20Radio/Firmware/src/ZiGate/Source

There is a chnaed file inside with "v3.0f" in comment.

**Comment by ruimarinho** [comment]
Yes, but there is no binary yet (only [3.0e](
https://github.com/fairecasoimeme/ZiGate/blob/master/Module%20Radio/Firmware/bin/ZiGate/ZiGate_Coordinator_v3.0e.bin)).

**Comment by pipiche38** [comment]
From the source I didn’t see yet the update to handle 24bits dataType so I suspect 3.0f is not yet finished 

Envoyé de mon iPhone

**Comment by Smanar** [comment]
Ha yep, sorry.
But now the code is open source, so we will have more often modifications without official release for beta testers.

**Comment by ruimarinho** [comment]
Ok, got it. Will close the issue. Do I need to Erase EEPROM and Complete EEPROM when upgrading to 3.0e?

Also, do I need to unpair devices before upgrading?
