### ISSUE TITLE
Support for Xiaomi Aqara Smart Curtain Motor

### ISSUE THREAD

**Issue by ruimarinho** [fairecasoimeme/ZiGate#83]
Hi @fairecasoimeme,

Do you have any plans for adding support to the [Aqara Curtain Switch Controller](https://www.gearbest.com/access-control/pp_626697.html)?

There is some work being done on https://github.com/Koenkk/zigbee2mqtt/issues/294 and some debug information available [here as well](https://github.com/TedTolboom/com.xiaomi-mi-zigbee/blob/master/drivers/curtain/device.js).

**Comment by pipiche38** [comment]
@ruimarinho my understanding is that it does work with Zigate, now it is up to the application or the plugin to handle it properly from a commands standpoint.

What is your system, which Zigate software are you using to inter-act with Zigate HW ?

**Comment by ruimarinho** [comment]
Ok, it is not specifically listed under [Xiaomi compatible devices](https://zigate.fr/produits-xiaomi-compatibles-zigate/) which is why I was asking.

> What is your system, which Zigate software are you using to inter-act with Zigate HW ?

Home Assistant using [doudz/homeassistant-zigate](https://github.com/doudz/homeassistant-zigate) plugin.

**Comment by pipiche38** [comment]
So then the best is to ask your question on the doudz side .

**Comment by ruimarinho** [comment]
Sure. Just wanted to know if there was anything needed on the Zigate side before working on the plugin.

**Comment by doudz** [comment]
As always, just try and let me know if there's a problem

**Comment by ruimarinho** [comment]
Fair enough. It will likely need a custom cover component but I will reopen this when I receive the device and it is ready for testing.
