### ISSUE TITLE
Remontée module 

### ISSUE THREAD

**Issue by Zejulien** [fairecasoimeme/ZiGate#88]
> Bonjour,
> Nouvel acquéreur de la ZiGate, je rencontre actuellement un problème.
> Dès lors que je retire une pile d'un module, si je remet la pile, alors le module ne fonctionne plus (même après redémarrage de Jeedom) .
> Exemple pour le capteur de fenêtre Aqara, si je retire la pile et que je la remet, même si j'appuie sur Resync et sur le bouton du capteur; alors rien ne se passe et le capteur reste à l'état "1".
> J'ai beau supprimer l'équipement et ressayer de le réappairer cela est sans effet. 
> 
> Avez-vous une idée de comment faire pour que lorsqu'une pile ou une coupure de courant à lieu pour que tout revienne à la normal lors du retour du courant/pile? 
> 
> Merci par avance,
> Bonne soirée

Je poste sur ce message sur le GitHub de Doudz

**Comment by max5962** [comment]
Hello,
Si tu coupes la pile ca reset le module.
Tu dois alors re-associer le module a la zigate
