### ISSUE TITLE
Limitation to 10 Xiaomi devices (firmwar 3.0a)

### ISSUE THREAD

**Issue by handfreezer** [fairecasoimeme/ZiGate#9]
Hello,

   As discussed, when no router is present, we can only associate 10 Xiaomi sensors (and not 60).

Best regards.

**Comment by fairecasoimeme** [comment]
Fixed on new version 3.0b.
- 50 direct devices and 80 max (with routers)

**Comment by handfreezer** [comment]
failed from me : I missed your answer.I just tried it, and it works : perfect!

**Comment by handfreezer** [comment]
THANKS!

**Comment by jordisalichs** [comment]
hi @handfreezer. How many Xiaomi sensors have you in your network? Do you lost any device?
Thank you
