### ISSUE TITLE
Add Group via ZGUI

### ISSUE THREAD

**Issue by pipiche38** [fairecasoimeme/ZiGate#94]
In ZGUI, 

Add Group doesn't look like the documented API in Zigate.fr 
ZGUI seems to expect Name Len Max Len and Group Name (which is not supported on Zigate)
Due to that if you try to add a device to a group via ZGUI with only the 4 first parameters you get an error
![image001](https://user-images.githubusercontent.com/8291674/49517161-c3005b80-f89b-11e8-8683-58331b5022ce.png)

**Comment by Smanar** [comment]
And if you put '0' on the 3 lasts case ?

**Comment by KiwiHC16** [comment]
I'm surprised because this paprt went smoothly in my implementation based on NXP doc (zigate is a copy of it).

**Comment by pipiche38** [comment]
For instance 0x8060 got more data than the only specified sqn, EP and cludterId

**Comment by pipiche38** [comment]
@Smanar I do confirm puting '0' in the 3 last boxes make the trick
