### ISSUE TITLE
Add Group response in Zigate.fr is uncomplete

### ISSUE THREAD

**Issue by pipiche38** [fairecasoimeme/ZiGate#96]
The documentation of the Add group response 0x8060 is uncomplete, 

The API is returning more and especiall a Status as well as the GroupID

```

        # ZNC_BUF_U8_UPD   ( &au8LinkTxBuffer [u16Length],pCustom->uMessage.psAddGroupResponsePayload->eStatus,       u16Length );
        # ZNC_BUF_U16_UPD  ( &au8LinkTxBuffer [u16Length],pCustom->uMessage.psAddGroupResponsePayload->u16GroupId,    u16Length );

        # 0180600008a98d0100048a00014203
        # Start: 01
        # Command: 8060
        # Leght: 0008
        # Checksum: a9
        # SQN: 8d
        # EP:        01
        # ClusterID        0004
        # Status:        8a
        # GroupID        0001
        # RSSI: 42
        # End: 03
```

**Comment by doudz** [comment]
yes you're right (again)

Maybe it could be useful to add the short addr in the response ?

**Comment by pipiche38** [comment]
@doudz if the information is available on the Zigate side, it would be indeed helpfull. 

I'm BTW wonder why the cluster is part, can we have something else than cluster 0x0004 ?

**Comment by doudz** [comment]
https://github.com/fairecasoimeme/ZiGate/pull/97

**Comment by pipiche38** [comment]
Excellent, thanks !

**Comment by doudz** [comment]
not tested since I can't compile the firmware...

**Comment by fairecasoimeme** [comment]
Fixed in 3.0f version

**Comment by pipiche38** [comment]
In the addgroupresponse, adding the Source Address is a good thing, but then the source addr must be added in order to be consisent.

**Comment by doudz** [comment]
What to you mean ? Source Address or source addr is the same thing, no ?

**Comment by pipiche38** [comment]
@doudz , my mistake ... no issue at all. I was under the impression that Source EP was missing. But that is not the case

**Comment by doudz** [comment]
ok...
