### ISSUE TITLE
Potential mistake in zigate.fr commande for 0x0047 Management Leave request

### ISSUE THREAD

**Issue by pipiche38** [fairecasoimeme/ZiGate#99]
Here after are the information for the Leave Indication Flag:
 Rejoin, 0 = Do not rejoin |   1 = Rejoin |  
 Remove Children |   | 0 = Leave, removing children  | 1 = Leave, do not remove children

Here is what I found in the documentation which seems the opposite:
typedef struct {
   uint64 u64DeviceAddress;
   uint8  u8Flags;
} ZPS_tsAplZdpMgmtLeaveReq;
where:
u64DeviceAddress is the IEEE address of the device being asked to leave the network  

u8Flags is an 8-bit bitmap containing the following flags:
Rejoin flag (bit 0): Set to 1 if the node requested to leave the network 
should immediately try to rejoin the network, otherwise set to 0.

**Remove Children flag (bit 1): Set to 1 if the node requested to leave the 
network should also request its own children (if any) to leave the network,  
otherwise set to 0**

**Comment by pipiche38** [comment]
Any update ?

**Comment by doudz** [comment]
I don't think there's a problem

> Rejoin flag (bit 0): Set to 1 if the node requested to leave the network
> should immediately try to rejoin the network, otherwise set to 0.

So Rejoin = 0 means not try to rejoin
Rejoin = 1 means try to rejoin

**Comment by pipiche38** [comment]
@Sebastien,

I'm fine with that. My issue is much more on the action towards the 
children

Statement 1: Remove Children |   | 0 = Leave, removing children | 1 = 
Leave, do not remove children

Statement 2: Remove Children flag (bit 1): Set to 1 if the node 
requested to leave the
network should also request its own children (if any) to leave the 
network,
otherwise set to 0

**Comment by doudz** [comment]
Sorry, read to fast ;)
I think you're right
https://github.com/fairecasoimeme/ZiGate/blob/d18f5e7e82f0660f909d144d217198f0468be072/Module%20Radio/Firmware/src/ZiGate/Source/ZigbeeNodeControlBridge/app_Znc_cmds.c#L2527

**Comment by pipiche38** [comment]
up , for documentation update

**Comment by fairecasoimeme** [comment]
Updated
